/*
 * generated by Xtext 2.41.0
 */
package elixir.of.things.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractElixirOfThingsValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(elixir.of.things.elixirOfThings.ElixirOfThingsPackage.eINSTANCE);
		return result;
	}
}
