/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool Not Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link elixir.of.things.elixirOfThings.BoolNotExpr#getOperand <em>Operand</em>}</li>
 * </ul>
 *
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getBoolNotExpr()
 * @model
 * @generated
 */
public interface BoolNotExpr extends BoolExpr
{
  /**
   * Returns the value of the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operand</em>' containment reference.
   * @see #setOperand(BoolExpr)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getBoolNotExpr_Operand()
   * @model containment="true"
   * @generated
   */
  BoolExpr getOperand();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.BoolNotExpr#getOperand <em>Operand</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operand</em>' containment reference.
   * @see #getOperand()
   * @generated
   */
  void setOperand(BoolExpr value);

} // BoolNotExpr
