/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
