/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link elixir.of.things.elixirOfThings.LiteralString#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getLiteralString()
 * @model
 * @generated
 */
public interface LiteralString extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getLiteralString_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.LiteralString#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // LiteralString
