/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Num Mul Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link elixir.of.things.elixirOfThings.NumMulExpr#getLeft <em>Left</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.NumMulExpr#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getNumMulExpr()
 * @model
 * @generated
 */
public interface NumMulExpr extends NumExpr
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(NumExpr)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getNumMulExpr_Left()
   * @model containment="true"
   * @generated
   */
  NumExpr getLeft();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.NumMulExpr#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(NumExpr value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(NumExpr)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getNumMulExpr_Right()
   * @model containment="true"
   * @generated
   */
  NumExpr getRight();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.NumMulExpr#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(NumExpr value);

} // NumMulExpr
