/*
 * generated by Xtext 2.41.0
 */
package elixir.of.things.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ElixirOfThingsGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class SystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.System");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSystemKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBrokerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBrokerBrokerParserRuleCall_3_0 = (RuleCall)cBrokerAssignment_3.eContents().get(0);
		private final Assignment cNodesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNodesNodeParserRuleCall_4_0 = (RuleCall)cNodesAssignment_4.eContents().get(0);
		private final Assignment cTopicsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTopicsTopicParserRuleCall_5_0 = (RuleCall)cTopicsAssignment_5.eContents().get(0);
		private final Alternatives cAlternatives_6 = (Alternatives)cGroup.eContents().get(6);
		private final Assignment cSensorsAssignment_6_0 = (Assignment)cAlternatives_6.eContents().get(0);
		private final RuleCall cSensorsSensorParserRuleCall_6_0_0 = (RuleCall)cSensorsAssignment_6_0.eContents().get(0);
		private final Assignment cActuatorsAssignment_6_1 = (Assignment)cAlternatives_6.eContents().get(1);
		private final RuleCall cActuatorsActuatorParserRuleCall_6_1_0 = (RuleCall)cActuatorsAssignment_6_1.eContents().get(0);
		private final Assignment cCoordinatorsAssignment_6_2 = (Assignment)cAlternatives_6.eContents().get(2);
		private final RuleCall cCoordinatorsCoordinatorParserRuleCall_6_2_0 = (RuleCall)cCoordinatorsAssignment_6_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//System:
		//    'system' name=ID '{'
		//        broker=Broker
		//        nodes+=Node+
		//        topics+=Topic*
		//        (sensors+=Sensor | actuators+=Actuator | coordinators+=Coordinator)*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'system' name=ID '{'
		//    broker=Broker
		//    nodes+=Node+
		//    topics+=Topic*
		//    (sensors+=Sensor | actuators+=Actuator | coordinators+=Coordinator)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'system'
		public Keyword getSystemKeyword_0() { return cSystemKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//broker=Broker
		public Assignment getBrokerAssignment_3() { return cBrokerAssignment_3; }
		
		//Broker
		public RuleCall getBrokerBrokerParserRuleCall_3_0() { return cBrokerBrokerParserRuleCall_3_0; }
		
		//nodes+=Node+
		public Assignment getNodesAssignment_4() { return cNodesAssignment_4; }
		
		//Node
		public RuleCall getNodesNodeParserRuleCall_4_0() { return cNodesNodeParserRuleCall_4_0; }
		
		//topics+=Topic*
		public Assignment getTopicsAssignment_5() { return cTopicsAssignment_5; }
		
		//Topic
		public RuleCall getTopicsTopicParserRuleCall_5_0() { return cTopicsTopicParserRuleCall_5_0; }
		
		//(sensors+=Sensor | actuators+=Actuator | coordinators+=Coordinator)*
		public Alternatives getAlternatives_6() { return cAlternatives_6; }
		
		//sensors+=Sensor
		public Assignment getSensorsAssignment_6_0() { return cSensorsAssignment_6_0; }
		
		//Sensor
		public RuleCall getSensorsSensorParserRuleCall_6_0_0() { return cSensorsSensorParserRuleCall_6_0_0; }
		
		//actuators+=Actuator
		public Assignment getActuatorsAssignment_6_1() { return cActuatorsAssignment_6_1; }
		
		//Actuator
		public RuleCall getActuatorsActuatorParserRuleCall_6_1_0() { return cActuatorsActuatorParserRuleCall_6_1_0; }
		
		//coordinators+=Coordinator
		public Assignment getCoordinatorsAssignment_6_2() { return cCoordinatorsAssignment_6_2; }
		
		//Coordinator
		public RuleCall getCoordinatorsCoordinatorParserRuleCall_6_2_0() { return cCoordinatorsCoordinatorParserRuleCall_6_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class BrokerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.Broker");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBrokerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHostAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cHostSTRINGTerminalRuleCall_1_0 = (RuleCall)cHostAssignment_1.eContents().get(0);
		private final Keyword cPortKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPortAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPortINTTerminalRuleCall_3_0 = (RuleCall)cPortAssignment_3.eContents().get(0);
		
		//Broker:
		//    'broker:' host=STRING 'port:' port=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'broker:' host=STRING 'port:' port=INT
		public Group getGroup() { return cGroup; }
		
		//'broker:'
		public Keyword getBrokerKeyword_0() { return cBrokerKeyword_0; }
		
		//host=STRING
		public Assignment getHostAssignment_1() { return cHostAssignment_1; }
		
		//STRING
		public RuleCall getHostSTRINGTerminalRuleCall_1_0() { return cHostSTRINGTerminalRuleCall_1_0; }
		
		//'port:'
		public Keyword getPortKeyword_2() { return cPortKeyword_2; }
		
		//port=INT
		public Assignment getPortAssignment_3() { return cPortAssignment_3; }
		
		//INT
		public RuleCall getPortINTTerminalRuleCall_3_0() { return cPortINTTerminalRuleCall_3_0; }
	}
	public class NodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.Node");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNodeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Node:
		//    'node' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'node' name=ID
		public Group getGroup() { return cGroup; }
		
		//'node'
		public Keyword getNodeKeyword_0() { return cNodeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class TopicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.Topic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTopicKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTopicStringAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTopicStringSTRINGTerminalRuleCall_4_0 = (RuleCall)cTopicStringAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cQosAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cQosQoSEnumRuleCall_6_0 = (RuleCall)cQosAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Topic:
		//    'topic' name=ID '=' '(' topicString=STRING ',' qos=QoS ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'topic' name=ID '=' '(' topicString=STRING ',' qos=QoS ')'
		public Group getGroup() { return cGroup; }
		
		//'topic'
		public Keyword getTopicKeyword_0() { return cTopicKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//topicString=STRING
		public Assignment getTopicStringAssignment_4() { return cTopicStringAssignment_4; }
		
		//STRING
		public RuleCall getTopicStringSTRINGTerminalRuleCall_4_0() { return cTopicStringSTRINGTerminalRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//qos=QoS
		public Assignment getQosAssignment_6() { return cQosAssignment_6; }
		
		//QoS
		public RuleCall getQosQoSEnumRuleCall_6_0() { return cQosQoSEnumRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
	}
	public class SensorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.Sensor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSensorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeSensorTypeEnumRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cGpioPinKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cGpioPinAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cGpioPinINTTerminalRuleCall_6_0 = (RuleCall)cGpioPinAssignment_6.eContents().get(0);
		private final Keyword cSampleRateKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cSampleRateAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSampleRateSampleRateParserRuleCall_8_0 = (RuleCall)cSampleRateAssignment_8.eContents().get(0);
		private final Keyword cDeployedOnKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDeployedOnAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cDeployedOnNodeCrossReference_10_0 = (CrossReference)cDeployedOnAssignment_10.eContents().get(0);
		private final RuleCall cDeployedOnNodeIDTerminalRuleCall_10_0_1 = (RuleCall)cDeployedOnNodeCrossReference_10_0.eContents().get(1);
		private final Assignment cTriggersAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cTriggersTriggerParserRuleCall_11_0 = (RuleCall)cTriggersAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Sensor:
		//    'sensor' name=ID '{'
		//        'type:' type=SensorType
		//        'gpioPin:' gpioPin=INT
		//        'sampleRate:' sampleRate=SampleRate
		//        'deployedOn:' deployedOn=[Node]
		//        triggers+=Trigger*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'sensor' name=ID '{'
		//    'type:' type=SensorType
		//    'gpioPin:' gpioPin=INT
		//    'sampleRate:' sampleRate=SampleRate
		//    'deployedOn:' deployedOn=[Node]
		//    triggers+=Trigger*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'sensor'
		public Keyword getSensorKeyword_0() { return cSensorKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type:'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=SensorType
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//SensorType
		public RuleCall getTypeSensorTypeEnumRuleCall_4_0() { return cTypeSensorTypeEnumRuleCall_4_0; }
		
		//'gpioPin:'
		public Keyword getGpioPinKeyword_5() { return cGpioPinKeyword_5; }
		
		//gpioPin=INT
		public Assignment getGpioPinAssignment_6() { return cGpioPinAssignment_6; }
		
		//INT
		public RuleCall getGpioPinINTTerminalRuleCall_6_0() { return cGpioPinINTTerminalRuleCall_6_0; }
		
		//'sampleRate:'
		public Keyword getSampleRateKeyword_7() { return cSampleRateKeyword_7; }
		
		//sampleRate=SampleRate
		public Assignment getSampleRateAssignment_8() { return cSampleRateAssignment_8; }
		
		//SampleRate
		public RuleCall getSampleRateSampleRateParserRuleCall_8_0() { return cSampleRateSampleRateParserRuleCall_8_0; }
		
		//'deployedOn:'
		public Keyword getDeployedOnKeyword_9() { return cDeployedOnKeyword_9; }
		
		//deployedOn=[Node]
		public Assignment getDeployedOnAssignment_10() { return cDeployedOnAssignment_10; }
		
		//[Node]
		public CrossReference getDeployedOnNodeCrossReference_10_0() { return cDeployedOnNodeCrossReference_10_0; }
		
		//ID
		public RuleCall getDeployedOnNodeIDTerminalRuleCall_10_0_1() { return cDeployedOnNodeIDTerminalRuleCall_10_0_1; }
		
		//triggers+=Trigger*
		public Assignment getTriggersAssignment_11() { return cTriggersAssignment_11; }
		
		//Trigger
		public RuleCall getTriggersTriggerParserRuleCall_11_0() { return cTriggersTriggerParserRuleCall_11_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class SampleRateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.SampleRate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cValueNumExprParserRuleCall_0_0 = (RuleCall)cValueAssignment_0.eContents().get(0);
		private final Assignment cUnitAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUnitTimeUnitEnumRuleCall_1_0 = (RuleCall)cUnitAssignment_1.eContents().get(0);
		
		//SampleRate:
		//    value=NumExpr unit=TimeUnit;
		@Override public ParserRule getRule() { return rule; }
		
		//value=NumExpr unit=TimeUnit
		public Group getGroup() { return cGroup; }
		
		//value=NumExpr
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }
		
		//NumExpr
		public RuleCall getValueNumExprParserRuleCall_0_0() { return cValueNumExprParserRuleCall_0_0; }
		
		//unit=TimeUnit
		public Assignment getUnitAssignment_1() { return cUnitAssignment_1; }
		
		//TimeUnit
		public RuleCall getUnitTimeUnitEnumRuleCall_1_0() { return cUnitTimeUnitEnumRuleCall_1_0; }
	}
	public class NumExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.NumExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cNumMulParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cNumAddExprLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cPlusSignKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cNumSubExprLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightNumMulParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//NumExpr returns NumExpr:
		//    NumMul (
		//        ({NumAddExpr.left=current} '+' | {NumSubExpr.left=current} '-')
		//        right=NumMul
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//NumMul (
		//    ({NumAddExpr.left=current} '+' | {NumSubExpr.left=current} '-')
		//    right=NumMul
		//)*
		public Group getGroup() { return cGroup; }
		
		//NumMul
		public RuleCall getNumMulParserRuleCall_0() { return cNumMulParserRuleCall_0; }
		
		//(
		//       ({NumAddExpr.left=current} '+' | {NumSubExpr.left=current} '-')
		//       right=NumMul
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//({NumAddExpr.left=current} '+' | {NumSubExpr.left=current} '-')
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{NumAddExpr.left=current} '+'
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{NumAddExpr.left=current}
		public Action getNumAddExprLeftAction_1_0_0_0() { return cNumAddExprLeftAction_1_0_0_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_1_0_0_1() { return cPlusSignKeyword_1_0_0_1; }
		
		//{NumSubExpr.left=current} '-'
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{NumSubExpr.left=current}
		public Action getNumSubExprLeftAction_1_0_1_0() { return cNumSubExprLeftAction_1_0_1_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1_0_1_1() { return cHyphenMinusKeyword_1_0_1_1; }
		
		//right=NumMul
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//NumMul
		public RuleCall getRightNumMulParserRuleCall_1_1_0() { return cRightNumMulParserRuleCall_1_1_0; }
	}
	public class NumMulElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.NumMul");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cNumAtomParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cAlternatives_1_0.eContents().get(0);
		private final Action cNumMulExprLeftAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Keyword cAsteriskKeyword_1_0_0_1 = (Keyword)cGroup_1_0_0.eContents().get(1);
		private final Group cGroup_1_0_1 = (Group)cAlternatives_1_0.eContents().get(1);
		private final Action cNumDivExprLeftAction_1_0_1_0 = (Action)cGroup_1_0_1.eContents().get(0);
		private final Keyword cSolidusKeyword_1_0_1_1 = (Keyword)cGroup_1_0_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightNumAtomParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//NumMul returns NumExpr:
		//    NumAtom (
		//        ({NumMulExpr.left=current} '*' | {NumDivExpr.left=current} '/')
		//        right=NumAtom
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//NumAtom (
		//    ({NumMulExpr.left=current} '*' | {NumDivExpr.left=current} '/')
		//    right=NumAtom
		//)*
		public Group getGroup() { return cGroup; }
		
		//NumAtom
		public RuleCall getNumAtomParserRuleCall_0() { return cNumAtomParserRuleCall_0; }
		
		//(
		//       ({NumMulExpr.left=current} '*' | {NumDivExpr.left=current} '/')
		//       right=NumAtom
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//({NumMulExpr.left=current} '*' | {NumDivExpr.left=current} '/')
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }
		
		//{NumMulExpr.left=current} '*'
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }
		
		//{NumMulExpr.left=current}
		public Action getNumMulExprLeftAction_1_0_0_0() { return cNumMulExprLeftAction_1_0_0_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_1_0_0_1() { return cAsteriskKeyword_1_0_0_1; }
		
		//{NumDivExpr.left=current} '/'
		public Group getGroup_1_0_1() { return cGroup_1_0_1; }
		
		//{NumDivExpr.left=current}
		public Action getNumDivExprLeftAction_1_0_1_0() { return cNumDivExprLeftAction_1_0_1_0; }
		
		//'/'
		public Keyword getSolidusKeyword_1_0_1_1() { return cSolidusKeyword_1_0_1_1; }
		
		//right=NumAtom
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//NumAtom
		public RuleCall getRightNumAtomParserRuleCall_1_1_0() { return cRightNumAtomParserRuleCall_1_1_0; }
	}
	public class NumAtomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.NumAtom");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cNumLiteralAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cNumExprParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//NumAtom returns NumExpr:
		//    {NumLiteral} value=INT |
		//    '(' NumExpr ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{NumLiteral} value=INT |
		//'(' NumExpr ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{NumLiteral} value=INT
		public Group getGroup_0() { return cGroup_0; }
		
		//{NumLiteral}
		public Action getNumLiteralAction_0_0() { return cNumLiteralAction_0_0; }
		
		//value=INT
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0_1_0() { return cValueINTTerminalRuleCall_0_1_0; }
		
		//'(' NumExpr ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//NumExpr
		public RuleCall getNumExprParserRuleCall_1_1() { return cNumExprParserRuleCall_1_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class TriggerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.Trigger");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTriggerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionTriggerConditionParserRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		private final Assignment cActionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cActionsTriggerActionParserRuleCall_4_0 = (RuleCall)cActionsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Trigger:
		//    'trigger' name=ID '{'
		//        condition=TriggerCondition
		//        actions+=TriggerAction+
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'trigger' name=ID '{'
		//    condition=TriggerCondition
		//    actions+=TriggerAction+
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'trigger'
		public Keyword getTriggerKeyword_0() { return cTriggerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//condition=TriggerCondition
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }
		
		//TriggerCondition
		public RuleCall getConditionTriggerConditionParserRuleCall_3_0() { return cConditionTriggerConditionParserRuleCall_3_0; }
		
		//actions+=TriggerAction+
		public Assignment getActionsAssignment_4() { return cActionsAssignment_4; }
		
		//TriggerAction
		public RuleCall getActionsTriggerActionParserRuleCall_4_0() { return cActionsTriggerActionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class TriggerConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.TriggerCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWhenKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cValueKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cOperatorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOperatorOperatorEnumRuleCall_2_0 = (RuleCall)cOperatorAssignment_2.eContents().get(0);
		private final Assignment cRightAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRightNumExprParserRuleCall_3_0 = (RuleCall)cRightAssignment_3.eContents().get(0);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//TriggerCondition:
		//    'when' 'value' operator=Operator right=NumExpr ':';
		@Override public ParserRule getRule() { return rule; }
		
		//'when' 'value' operator=Operator right=NumExpr ':'
		public Group getGroup() { return cGroup; }
		
		//'when'
		public Keyword getWhenKeyword_0() { return cWhenKeyword_0; }
		
		//'value'
		public Keyword getValueKeyword_1() { return cValueKeyword_1; }
		
		//operator=Operator
		public Assignment getOperatorAssignment_2() { return cOperatorAssignment_2; }
		
		//Operator
		public RuleCall getOperatorOperatorEnumRuleCall_2_0() { return cOperatorOperatorEnumRuleCall_2_0; }
		
		//right=NumExpr
		public Assignment getRightAssignment_3() { return cRightAssignment_3; }
		
		//NumExpr
		public RuleCall getRightNumExprParserRuleCall_3_0() { return cRightNumExprParserRuleCall_3_0; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
	}
	public class TriggerActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.TriggerAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPublishKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTopicAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTopicTopicCrossReference_1_0 = (CrossReference)cTopicAssignment_1.eContents().get(0);
		private final RuleCall cTopicTopicIDTerminalRuleCall_1_0_1 = (RuleCall)cTopicTopicCrossReference_1_0.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFieldsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFieldsPublishFieldParserRuleCall_4_0 = (RuleCall)cFieldsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cFieldsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cFieldsPublishFieldParserRuleCall_5_1_0 = (RuleCall)cFieldsAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//TriggerAction:
		//    'publish' topic=[Topic] ':' '{' fields+=PublishField (',' fields+=PublishField)* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'publish' topic=[Topic] ':' '{' fields+=PublishField (',' fields+=PublishField)* '}'
		public Group getGroup() { return cGroup; }
		
		//'publish'
		public Keyword getPublishKeyword_0() { return cPublishKeyword_0; }
		
		//topic=[Topic]
		public Assignment getTopicAssignment_1() { return cTopicAssignment_1; }
		
		//[Topic]
		public CrossReference getTopicTopicCrossReference_1_0() { return cTopicTopicCrossReference_1_0; }
		
		//ID
		public RuleCall getTopicTopicIDTerminalRuleCall_1_0_1() { return cTopicTopicIDTerminalRuleCall_1_0_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//fields+=PublishField
		public Assignment getFieldsAssignment_4() { return cFieldsAssignment_4; }
		
		//PublishField
		public RuleCall getFieldsPublishFieldParserRuleCall_4_0() { return cFieldsPublishFieldParserRuleCall_4_0; }
		
		//(',' fields+=PublishField)*
		public Group getGroup_5() { return cGroup_5; }
		
		//','
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//fields+=PublishField
		public Assignment getFieldsAssignment_5_1() { return cFieldsAssignment_5_1; }
		
		//PublishField
		public RuleCall getFieldsPublishFieldParserRuleCall_5_1_0() { return cFieldsPublishFieldParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class PublishFieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.PublishField");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cValueFieldAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cValueKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cTimestampFieldAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cTimestampKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//PublishField:
		//    {ValueField}     'value'     |
		//    {TimestampField} 'timestamp';
		@Override public ParserRule getRule() { return rule; }
		
		//{ValueField}     'value'     |
		//{TimestampField} 'timestamp'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{ValueField}     'value'
		public Group getGroup_0() { return cGroup_0; }
		
		//{ValueField}
		public Action getValueFieldAction_0_0() { return cValueFieldAction_0_0; }
		
		//'value'
		public Keyword getValueKeyword_0_1() { return cValueKeyword_0_1; }
		
		//{TimestampField} 'timestamp'
		public Group getGroup_1() { return cGroup_1; }
		
		//{TimestampField}
		public Action getTimestampFieldAction_1_0() { return cTimestampFieldAction_1_0; }
		
		//'timestamp'
		public Keyword getTimestampKeyword_1_1() { return cTimestampKeyword_1_1; }
	}
	public class ActuatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.Actuator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActuatorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeActuatorTypeEnumRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cGpioPinKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cGpioPinAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cGpioPinINTTerminalRuleCall_6_0 = (RuleCall)cGpioPinAssignment_6.eContents().get(0);
		private final Keyword cDeployedOnKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDeployedOnAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cDeployedOnNodeCrossReference_8_0 = (CrossReference)cDeployedOnAssignment_8.eContents().get(0);
		private final RuleCall cDeployedOnNodeIDTerminalRuleCall_8_0_1 = (RuleCall)cDeployedOnNodeCrossReference_8_0.eContents().get(1);
		private final Keyword cSubscribeToKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cSubscribeToAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cSubscribeToTopicCrossReference_10_0 = (CrossReference)cSubscribeToAssignment_10.eContents().get(0);
		private final RuleCall cSubscribeToTopicIDTerminalRuleCall_10_0_1 = (RuleCall)cSubscribeToTopicCrossReference_10_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cSubscribeToAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cSubscribeToTopicCrossReference_11_1_0 = (CrossReference)cSubscribeToAssignment_11_1.eContents().get(0);
		private final RuleCall cSubscribeToTopicIDTerminalRuleCall_11_1_0_1 = (RuleCall)cSubscribeToTopicCrossReference_11_1_0.eContents().get(1);
		private final Assignment cMessagesAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cMessagesOnMessageParserRuleCall_12_0 = (RuleCall)cMessagesAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Actuator:
		//    'actuator' name=ID '{'
		//        'type:' type=ActuatorType
		//        'gpioPin:' gpioPin=INT
		//        'deployedOn:' deployedOn=[Node]
		//        'subscribeTo:' subscribeTo+=[Topic] (',' subscribeTo+=[Topic])*
		//        messages+=OnMessage*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'actuator' name=ID '{'
		//    'type:' type=ActuatorType
		//    'gpioPin:' gpioPin=INT
		//    'deployedOn:' deployedOn=[Node]
		//    'subscribeTo:' subscribeTo+=[Topic] (',' subscribeTo+=[Topic])*
		//    messages+=OnMessage*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'actuator'
		public Keyword getActuatorKeyword_0() { return cActuatorKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type:'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=ActuatorType
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//ActuatorType
		public RuleCall getTypeActuatorTypeEnumRuleCall_4_0() { return cTypeActuatorTypeEnumRuleCall_4_0; }
		
		//'gpioPin:'
		public Keyword getGpioPinKeyword_5() { return cGpioPinKeyword_5; }
		
		//gpioPin=INT
		public Assignment getGpioPinAssignment_6() { return cGpioPinAssignment_6; }
		
		//INT
		public RuleCall getGpioPinINTTerminalRuleCall_6_0() { return cGpioPinINTTerminalRuleCall_6_0; }
		
		//'deployedOn:'
		public Keyword getDeployedOnKeyword_7() { return cDeployedOnKeyword_7; }
		
		//deployedOn=[Node]
		public Assignment getDeployedOnAssignment_8() { return cDeployedOnAssignment_8; }
		
		//[Node]
		public CrossReference getDeployedOnNodeCrossReference_8_0() { return cDeployedOnNodeCrossReference_8_0; }
		
		//ID
		public RuleCall getDeployedOnNodeIDTerminalRuleCall_8_0_1() { return cDeployedOnNodeIDTerminalRuleCall_8_0_1; }
		
		//'subscribeTo:'
		public Keyword getSubscribeToKeyword_9() { return cSubscribeToKeyword_9; }
		
		//subscribeTo+=[Topic]
		public Assignment getSubscribeToAssignment_10() { return cSubscribeToAssignment_10; }
		
		//[Topic]
		public CrossReference getSubscribeToTopicCrossReference_10_0() { return cSubscribeToTopicCrossReference_10_0; }
		
		//ID
		public RuleCall getSubscribeToTopicIDTerminalRuleCall_10_0_1() { return cSubscribeToTopicIDTerminalRuleCall_10_0_1; }
		
		//(',' subscribeTo+=[Topic])*
		public Group getGroup_11() { return cGroup_11; }
		
		//','
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }
		
		//subscribeTo+=[Topic]
		public Assignment getSubscribeToAssignment_11_1() { return cSubscribeToAssignment_11_1; }
		
		//[Topic]
		public CrossReference getSubscribeToTopicCrossReference_11_1_0() { return cSubscribeToTopicCrossReference_11_1_0; }
		
		//ID
		public RuleCall getSubscribeToTopicIDTerminalRuleCall_11_1_0_1() { return cSubscribeToTopicIDTerminalRuleCall_11_1_0_1; }
		
		//messages+=OnMessage*
		public Assignment getMessagesAssignment_12() { return cMessagesAssignment_12; }
		
		//OnMessage
		public RuleCall getMessagesOnMessageParserRuleCall_12_0() { return cMessagesOnMessageParserRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class OnMessageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.OnMessage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOnKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMessageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFromKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTopicAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cTopicTopicCrossReference_3_0 = (CrossReference)cTopicAssignment_3.eContents().get(0);
		private final RuleCall cTopicTopicIDTerminalRuleCall_3_0_1 = (RuleCall)cTopicTopicCrossReference_3_0.eContents().get(1);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cTurnKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStateAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStateStateEnumRuleCall_6_0 = (RuleCall)cStateAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cForKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cDurationAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cDurationSampleRateParserRuleCall_7_1_0 = (RuleCall)cDurationAssignment_7_1.eContents().get(0);
		
		//OnMessage:
		//    'on' 'message' 'from' topic=[Topic] ':'
		//        'turn' state=State ('for' duration=SampleRate)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'on' 'message' 'from' topic=[Topic] ':'
		//    'turn' state=State ('for' duration=SampleRate)?
		public Group getGroup() { return cGroup; }
		
		//'on'
		public Keyword getOnKeyword_0() { return cOnKeyword_0; }
		
		//'message'
		public Keyword getMessageKeyword_1() { return cMessageKeyword_1; }
		
		//'from'
		public Keyword getFromKeyword_2() { return cFromKeyword_2; }
		
		//topic=[Topic]
		public Assignment getTopicAssignment_3() { return cTopicAssignment_3; }
		
		//[Topic]
		public CrossReference getTopicTopicCrossReference_3_0() { return cTopicTopicCrossReference_3_0; }
		
		//ID
		public RuleCall getTopicTopicIDTerminalRuleCall_3_0_1() { return cTopicTopicIDTerminalRuleCall_3_0_1; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//'turn'
		public Keyword getTurnKeyword_5() { return cTurnKeyword_5; }
		
		//state=State
		public Assignment getStateAssignment_6() { return cStateAssignment_6; }
		
		//State
		public RuleCall getStateStateEnumRuleCall_6_0() { return cStateStateEnumRuleCall_6_0; }
		
		//('for' duration=SampleRate)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'for'
		public Keyword getForKeyword_7_0() { return cForKeyword_7_0; }
		
		//duration=SampleRate
		public Assignment getDurationAssignment_7_1() { return cDurationAssignment_7_1; }
		
		//SampleRate
		public RuleCall getDurationSampleRateParserRuleCall_7_1_0() { return cDurationSampleRateParserRuleCall_7_1_0; }
	}
	public class CoordinatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.Coordinator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCoordinatorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDeployedOnKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDeployedOnAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cDeployedOnNodeCrossReference_4_0 = (CrossReference)cDeployedOnAssignment_4.eContents().get(0);
		private final RuleCall cDeployedOnNodeIDTerminalRuleCall_4_0_1 = (RuleCall)cDeployedOnNodeCrossReference_4_0.eContents().get(1);
		private final Keyword cSubscribeToKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSubscribeToAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSubscribeToTopicCrossReference_6_0 = (CrossReference)cSubscribeToAssignment_6.eContents().get(0);
		private final RuleCall cSubscribeToTopicIDTerminalRuleCall_6_0_1 = (RuleCall)cSubscribeToTopicCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSubscribeToAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cSubscribeToTopicCrossReference_7_1_0 = (CrossReference)cSubscribeToAssignment_7_1.eContents().get(0);
		private final RuleCall cSubscribeToTopicIDTerminalRuleCall_7_1_0_1 = (RuleCall)cSubscribeToTopicCrossReference_7_1_0.eContents().get(1);
		private final Assignment cRulesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cRulesRuleParserRuleCall_8_0 = (RuleCall)cRulesAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Coordinator:
		//    'coordinator' name=ID '{'
		//        'deployedOn:' deployedOn=[Node]
		//        'subscribeTo:' subscribeTo+=[Topic] (',' subscribeTo+=[Topic])*
		//        rules+=Rule*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'coordinator' name=ID '{'
		//    'deployedOn:' deployedOn=[Node]
		//    'subscribeTo:' subscribeTo+=[Topic] (',' subscribeTo+=[Topic])*
		//    rules+=Rule*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'coordinator'
		public Keyword getCoordinatorKeyword_0() { return cCoordinatorKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'deployedOn:'
		public Keyword getDeployedOnKeyword_3() { return cDeployedOnKeyword_3; }
		
		//deployedOn=[Node]
		public Assignment getDeployedOnAssignment_4() { return cDeployedOnAssignment_4; }
		
		//[Node]
		public CrossReference getDeployedOnNodeCrossReference_4_0() { return cDeployedOnNodeCrossReference_4_0; }
		
		//ID
		public RuleCall getDeployedOnNodeIDTerminalRuleCall_4_0_1() { return cDeployedOnNodeIDTerminalRuleCall_4_0_1; }
		
		//'subscribeTo:'
		public Keyword getSubscribeToKeyword_5() { return cSubscribeToKeyword_5; }
		
		//subscribeTo+=[Topic]
		public Assignment getSubscribeToAssignment_6() { return cSubscribeToAssignment_6; }
		
		//[Topic]
		public CrossReference getSubscribeToTopicCrossReference_6_0() { return cSubscribeToTopicCrossReference_6_0; }
		
		//ID
		public RuleCall getSubscribeToTopicIDTerminalRuleCall_6_0_1() { return cSubscribeToTopicIDTerminalRuleCall_6_0_1; }
		
		//(',' subscribeTo+=[Topic])*
		public Group getGroup_7() { return cGroup_7; }
		
		//','
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//subscribeTo+=[Topic]
		public Assignment getSubscribeToAssignment_7_1() { return cSubscribeToAssignment_7_1; }
		
		//[Topic]
		public CrossReference getSubscribeToTopicCrossReference_7_1_0() { return cSubscribeToTopicCrossReference_7_1_0; }
		
		//ID
		public RuleCall getSubscribeToTopicIDTerminalRuleCall_7_1_0_1() { return cSubscribeToTopicIDTerminalRuleCall_7_1_0_1; }
		
		//rules+=Rule*
		public Assignment getRulesAssignment_8() { return cRulesAssignment_8; }
		
		//Rule
		public RuleCall getRulesRuleParserRuleCall_8_0() { return cRulesRuleParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class RuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.Rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionRuleConditionParserRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		private final Assignment cActionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cActionsRuleActionParserRuleCall_4_0 = (RuleCall)cActionsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Rule:
		//    'rule' name=ID '{'
		//        condition=RuleCondition
		//        actions+=RuleAction+
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'rule' name=ID '{'
		//    condition=RuleCondition
		//    actions+=RuleAction+
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'rule'
		public Keyword getRuleKeyword_0() { return cRuleKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//condition=RuleCondition
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }
		
		//RuleCondition
		public RuleCall getConditionRuleConditionParserRuleCall_3_0() { return cConditionRuleConditionParserRuleCall_3_0; }
		
		//actions+=RuleAction+
		public Assignment getActionsAssignment_4() { return cActionsAssignment_4; }
		
		//RuleAction
		public RuleCall getActionsRuleActionParserRuleCall_4_0() { return cActionsRuleActionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class RuleConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.RuleCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWhenKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cExpressionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpressionBoolOrParserRuleCall_1_0 = (RuleCall)cExpressionAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//RuleCondition:
		//    'when' expression=BoolOr ':';
		@Override public ParserRule getRule() { return rule; }
		
		//'when' expression=BoolOr ':'
		public Group getGroup() { return cGroup; }
		
		//'when'
		public Keyword getWhenKeyword_0() { return cWhenKeyword_0; }
		
		//expression=BoolOr
		public Assignment getExpressionAssignment_1() { return cExpressionAssignment_1; }
		
		//BoolOr
		public RuleCall getExpressionBoolOrParserRuleCall_1_0() { return cExpressionBoolOrParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
	}
	public class BoolOrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.BoolOr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cBoolAndParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBoolOrExprLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cOrKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightBoolAndParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//BoolOr returns BoolExpr:
		//    BoolAnd ({BoolOrExpr.left=current} 'or' right=BoolAnd)*;
		@Override public ParserRule getRule() { return rule; }
		
		//BoolAnd ({BoolOrExpr.left=current} 'or' right=BoolAnd)*
		public Group getGroup() { return cGroup; }
		
		//BoolAnd
		public RuleCall getBoolAndParserRuleCall_0() { return cBoolAndParserRuleCall_0; }
		
		//({BoolOrExpr.left=current} 'or' right=BoolAnd)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{BoolOrExpr.left=current}
		public Action getBoolOrExprLeftAction_1_0() { return cBoolOrExprLeftAction_1_0; }
		
		//'or'
		public Keyword getOrKeyword_1_1() { return cOrKeyword_1_1; }
		
		//right=BoolAnd
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//BoolAnd
		public RuleCall getRightBoolAndParserRuleCall_1_2_0() { return cRightBoolAndParserRuleCall_1_2_0; }
	}
	public class BoolAndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.BoolAnd");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cBoolNotParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBoolAndExprLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cAndKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightBoolNotParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//BoolAnd returns BoolExpr:
		//    BoolNot ({BoolAndExpr.left=current} 'and' right=BoolNot)*;
		@Override public ParserRule getRule() { return rule; }
		
		//BoolNot ({BoolAndExpr.left=current} 'and' right=BoolNot)*
		public Group getGroup() { return cGroup; }
		
		//BoolNot
		public RuleCall getBoolNotParserRuleCall_0() { return cBoolNotParserRuleCall_0; }
		
		//({BoolAndExpr.left=current} 'and' right=BoolNot)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{BoolAndExpr.left=current}
		public Action getBoolAndExprLeftAction_1_0() { return cBoolAndExprLeftAction_1_0; }
		
		//'and'
		public Keyword getAndKeyword_1_1() { return cAndKeyword_1_1; }
		
		//right=BoolNot
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//BoolNot
		public RuleCall getRightBoolNotParserRuleCall_1_2_0() { return cRightBoolNotParserRuleCall_1_2_0; }
	}
	public class BoolNotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.BoolNot");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cBoolNotExprAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cNotKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cOperandAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cOperandBoolAtomParserRuleCall_0_2_0 = (RuleCall)cOperandAssignment_0_2.eContents().get(0);
		private final RuleCall cBoolAtomParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//BoolNot returns BoolExpr:
		//    {BoolNotExpr} 'not' operand=BoolAtom |
		//    BoolAtom;
		@Override public ParserRule getRule() { return rule; }
		
		//{BoolNotExpr} 'not' operand=BoolAtom |
		//BoolAtom
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{BoolNotExpr} 'not' operand=BoolAtom
		public Group getGroup_0() { return cGroup_0; }
		
		//{BoolNotExpr}
		public Action getBoolNotExprAction_0_0() { return cBoolNotExprAction_0_0; }
		
		//'not'
		public Keyword getNotKeyword_0_1() { return cNotKeyword_0_1; }
		
		//operand=BoolAtom
		public Assignment getOperandAssignment_0_2() { return cOperandAssignment_0_2; }
		
		//BoolAtom
		public RuleCall getOperandBoolAtomParserRuleCall_0_2_0() { return cOperandBoolAtomParserRuleCall_0_2_0; }
		
		//BoolAtom
		public RuleCall getBoolAtomParserRuleCall_1() { return cBoolAtomParserRuleCall_1; }
	}
	public class BoolAtomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.BoolAtom");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cTopicRefAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cTopicAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final CrossReference cTopicTopicCrossReference_0_1_0 = (CrossReference)cTopicAssignment_0_1.eContents().get(0);
		private final RuleCall cTopicTopicIDTerminalRuleCall_0_1_0_1 = (RuleCall)cTopicTopicCrossReference_0_1_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cBoolOrParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//BoolAtom returns BoolExpr:
		//    {TopicRef} topic=[Topic] |
		//    '(' BoolOr ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{TopicRef} topic=[Topic] |
		//'(' BoolOr ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{TopicRef} topic=[Topic]
		public Group getGroup_0() { return cGroup_0; }
		
		//{TopicRef}
		public Action getTopicRefAction_0_0() { return cTopicRefAction_0_0; }
		
		//topic=[Topic]
		public Assignment getTopicAssignment_0_1() { return cTopicAssignment_0_1; }
		
		//[Topic]
		public CrossReference getTopicTopicCrossReference_0_1_0() { return cTopicTopicCrossReference_0_1_0; }
		
		//ID
		public RuleCall getTopicTopicIDTerminalRuleCall_0_1_0_1() { return cTopicTopicIDTerminalRuleCall_0_1_0_1; }
		
		//'(' BoolOr ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//BoolOr
		public RuleCall getBoolOrParserRuleCall_1_1() { return cBoolOrParserRuleCall_1_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class RuleActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.RuleAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPublishKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTopicAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTopicTopicCrossReference_1_0 = (CrossReference)cTopicAssignment_1.eContents().get(0);
		private final RuleCall cTopicTopicIDTerminalRuleCall_1_0_1 = (RuleCall)cTopicTopicCrossReference_1_0.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMessageKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMessageAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cMessageSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cMessageAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//RuleAction:
		//    'publish' topic=[Topic] ':' '{' ('message:' message=STRING)? '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'publish' topic=[Topic] ':' '{' ('message:' message=STRING)? '}'
		public Group getGroup() { return cGroup; }
		
		//'publish'
		public Keyword getPublishKeyword_0() { return cPublishKeyword_0; }
		
		//topic=[Topic]
		public Assignment getTopicAssignment_1() { return cTopicAssignment_1; }
		
		//[Topic]
		public CrossReference getTopicTopicCrossReference_1_0() { return cTopicTopicCrossReference_1_0; }
		
		//ID
		public RuleCall getTopicTopicIDTerminalRuleCall_1_0_1() { return cTopicTopicIDTerminalRuleCall_1_0_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('message:' message=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'message:'
		public Keyword getMessageKeyword_4_0() { return cMessageKeyword_4_0; }
		
		//message=STRING
		public Assignment getMessageAssignment_4_1() { return cMessageAssignment_4_1; }
		
		//STRING
		public RuleCall getMessageSTRINGTerminalRuleCall_4_1_0() { return cMessageSTRINGTerminalRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	public class SensorTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.SensorType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTEMP_DS18B20EnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTEMP_DS18B20TEMP_DS18B20Keyword_0_0 = (Keyword)cTEMP_DS18B20EnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTEMP_DHT22EnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTEMP_DHT22TEMP_DHT22Keyword_1_0 = (Keyword)cTEMP_DHT22EnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cHUMIDITYEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cHUMIDITYHUMIDITYKeyword_2_0 = (Keyword)cHUMIDITYEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMOTION_PIREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMOTION_PIRMOTION_PIRKeyword_3_0 = (Keyword)cMOTION_PIREnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cLIGHTEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cLIGHTLIGHTKeyword_4_0 = (Keyword)cLIGHTEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cDISTANCEEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cDISTANCEDISTANCEKeyword_5_0 = (Keyword)cDISTANCEEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum SensorType:
		//    TEMP_DS18B20 | TEMP_DHT22 | HUMIDITY | MOTION_PIR | LIGHT | DISTANCE;
		public EnumRule getRule() { return rule; }
		
		//TEMP_DS18B20 | TEMP_DHT22 | HUMIDITY | MOTION_PIR | LIGHT | DISTANCE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TEMP_DS18B20
		public EnumLiteralDeclaration getTEMP_DS18B20EnumLiteralDeclaration_0() { return cTEMP_DS18B20EnumLiteralDeclaration_0; }
		
		public Keyword getTEMP_DS18B20TEMP_DS18B20Keyword_0_0() { return cTEMP_DS18B20TEMP_DS18B20Keyword_0_0; }
		
		//TEMP_DHT22
		public EnumLiteralDeclaration getTEMP_DHT22EnumLiteralDeclaration_1() { return cTEMP_DHT22EnumLiteralDeclaration_1; }
		
		public Keyword getTEMP_DHT22TEMP_DHT22Keyword_1_0() { return cTEMP_DHT22TEMP_DHT22Keyword_1_0; }
		
		//HUMIDITY
		public EnumLiteralDeclaration getHUMIDITYEnumLiteralDeclaration_2() { return cHUMIDITYEnumLiteralDeclaration_2; }
		
		public Keyword getHUMIDITYHUMIDITYKeyword_2_0() { return cHUMIDITYHUMIDITYKeyword_2_0; }
		
		//MOTION_PIR
		public EnumLiteralDeclaration getMOTION_PIREnumLiteralDeclaration_3() { return cMOTION_PIREnumLiteralDeclaration_3; }
		
		public Keyword getMOTION_PIRMOTION_PIRKeyword_3_0() { return cMOTION_PIRMOTION_PIRKeyword_3_0; }
		
		//LIGHT
		public EnumLiteralDeclaration getLIGHTEnumLiteralDeclaration_4() { return cLIGHTEnumLiteralDeclaration_4; }
		
		public Keyword getLIGHTLIGHTKeyword_4_0() { return cLIGHTLIGHTKeyword_4_0; }
		
		//DISTANCE
		public EnumLiteralDeclaration getDISTANCEEnumLiteralDeclaration_5() { return cDISTANCEEnumLiteralDeclaration_5; }
		
		public Keyword getDISTANCEDISTANCEKeyword_5_0() { return cDISTANCEDISTANCEKeyword_5_0; }
	}
	public class ActuatorTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.ActuatorType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cRELAYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cRELAYRELAYKeyword_0_0 = (Keyword)cRELAYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLEDLEDKeyword_1_0 = (Keyword)cLEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBUZZEREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBUZZERBUZZERKeyword_2_0 = (Keyword)cBUZZEREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSERVOEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSERVOSERVOKeyword_3_0 = (Keyword)cSERVOEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum ActuatorType:
		//    RELAY | LED | BUZZER | SERVO;
		public EnumRule getRule() { return rule; }
		
		//RELAY | LED | BUZZER | SERVO
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//RELAY
		public EnumLiteralDeclaration getRELAYEnumLiteralDeclaration_0() { return cRELAYEnumLiteralDeclaration_0; }
		
		public Keyword getRELAYRELAYKeyword_0_0() { return cRELAYRELAYKeyword_0_0; }
		
		//LED
		public EnumLiteralDeclaration getLEDEnumLiteralDeclaration_1() { return cLEDEnumLiteralDeclaration_1; }
		
		public Keyword getLEDLEDKeyword_1_0() { return cLEDLEDKeyword_1_0; }
		
		//BUZZER
		public EnumLiteralDeclaration getBUZZEREnumLiteralDeclaration_2() { return cBUZZEREnumLiteralDeclaration_2; }
		
		public Keyword getBUZZERBUZZERKeyword_2_0() { return cBUZZERBUZZERKeyword_2_0; }
		
		//SERVO
		public EnumLiteralDeclaration getSERVOEnumLiteralDeclaration_3() { return cSERVOEnumLiteralDeclaration_3; }
		
		public Keyword getSERVOSERVOKeyword_3_0() { return cSERVOSERVOKeyword_3_0; }
	}
	public class QoSElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.QoS");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAT_MOST_ONCEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAT_MOST_ONCEAT_MOST_ONCEKeyword_0_0 = (Keyword)cAT_MOST_ONCEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAT_LEAST_ONCEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAT_LEAST_ONCEAT_LEAST_ONCEKeyword_1_0 = (Keyword)cAT_LEAST_ONCEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cEXACTLY_ONCEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cEXACTLY_ONCEEXACTLY_ONCEKeyword_2_0 = (Keyword)cEXACTLY_ONCEEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum QoS:
		//    AT_MOST_ONCE | AT_LEAST_ONCE | EXACTLY_ONCE;
		public EnumRule getRule() { return rule; }
		
		//AT_MOST_ONCE | AT_LEAST_ONCE | EXACTLY_ONCE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AT_MOST_ONCE
		public EnumLiteralDeclaration getAT_MOST_ONCEEnumLiteralDeclaration_0() { return cAT_MOST_ONCEEnumLiteralDeclaration_0; }
		
		public Keyword getAT_MOST_ONCEAT_MOST_ONCEKeyword_0_0() { return cAT_MOST_ONCEAT_MOST_ONCEKeyword_0_0; }
		
		//AT_LEAST_ONCE
		public EnumLiteralDeclaration getAT_LEAST_ONCEEnumLiteralDeclaration_1() { return cAT_LEAST_ONCEEnumLiteralDeclaration_1; }
		
		public Keyword getAT_LEAST_ONCEAT_LEAST_ONCEKeyword_1_0() { return cAT_LEAST_ONCEAT_LEAST_ONCEKeyword_1_0; }
		
		//EXACTLY_ONCE
		public EnumLiteralDeclaration getEXACTLY_ONCEEnumLiteralDeclaration_2() { return cEXACTLY_ONCEEnumLiteralDeclaration_2; }
		
		public Keyword getEXACTLY_ONCEEXACTLY_ONCEKeyword_2_0() { return cEXACTLY_ONCEEXACTLY_ONCEKeyword_2_0; }
	}
	public class OperatorElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.Operator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cGREATER_THANEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cGREATER_THANGreaterThanSignKeyword_0_0 = (Keyword)cGREATER_THANEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLESS_THANEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLESS_THANLessThanSignKeyword_1_0 = (Keyword)cLESS_THANEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cGREATER_EQEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cGREATER_EQGreaterThanSignEqualsSignKeyword_2_0 = (Keyword)cGREATER_EQEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cLESS_EQEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cLESS_EQLessThanSignEqualsSignKeyword_3_0 = (Keyword)cLESS_EQEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cEQUALSEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cEQUALSEqualsSignEqualsSignKeyword_4_0 = (Keyword)cEQUALSEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Operator:
		//    GREATER_THAN='>' | LESS_THAN='<' | GREATER_EQ='>=' | LESS_EQ='<=' | EQUALS='==';
		public EnumRule getRule() { return rule; }
		
		//GREATER_THAN='>' | LESS_THAN='<' | GREATER_EQ='>=' | LESS_EQ='<=' | EQUALS='=='
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//GREATER_THAN='>'
		public EnumLiteralDeclaration getGREATER_THANEnumLiteralDeclaration_0() { return cGREATER_THANEnumLiteralDeclaration_0; }
		
		//'>'
		public Keyword getGREATER_THANGreaterThanSignKeyword_0_0() { return cGREATER_THANGreaterThanSignKeyword_0_0; }
		
		//LESS_THAN='<'
		public EnumLiteralDeclaration getLESS_THANEnumLiteralDeclaration_1() { return cLESS_THANEnumLiteralDeclaration_1; }
		
		//'<'
		public Keyword getLESS_THANLessThanSignKeyword_1_0() { return cLESS_THANLessThanSignKeyword_1_0; }
		
		//GREATER_EQ='>='
		public EnumLiteralDeclaration getGREATER_EQEnumLiteralDeclaration_2() { return cGREATER_EQEnumLiteralDeclaration_2; }
		
		//'>='
		public Keyword getGREATER_EQGreaterThanSignEqualsSignKeyword_2_0() { return cGREATER_EQGreaterThanSignEqualsSignKeyword_2_0; }
		
		//LESS_EQ='<='
		public EnumLiteralDeclaration getLESS_EQEnumLiteralDeclaration_3() { return cLESS_EQEnumLiteralDeclaration_3; }
		
		//'<='
		public Keyword getLESS_EQLessThanSignEqualsSignKeyword_3_0() { return cLESS_EQLessThanSignEqualsSignKeyword_3_0; }
		
		//EQUALS='=='
		public EnumLiteralDeclaration getEQUALSEnumLiteralDeclaration_4() { return cEQUALSEnumLiteralDeclaration_4; }
		
		//'=='
		public Keyword getEQUALSEqualsSignEqualsSignKeyword_4_0() { return cEQUALSEqualsSignEqualsSignKeyword_4_0; }
	}
	public class StateElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.State");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cONEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cONONKeyword_0_0 = (Keyword)cONEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOFFEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOFFOFFKeyword_1_0 = (Keyword)cOFFEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum State:
		//    ON | OFF;
		public EnumRule getRule() { return rule; }
		
		//ON | OFF
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ON
		public EnumLiteralDeclaration getONEnumLiteralDeclaration_0() { return cONEnumLiteralDeclaration_0; }
		
		public Keyword getONONKeyword_0_0() { return cONONKeyword_0_0; }
		
		//OFF
		public EnumLiteralDeclaration getOFFEnumLiteralDeclaration_1() { return cOFFEnumLiteralDeclaration_1; }
		
		public Keyword getOFFOFFKeyword_1_0() { return cOFFOFFKeyword_1_0; }
	}
	public class TimeUnitElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "elixir.of.things.ElixirOfThings.TimeUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSECEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSECSecKeyword_0_0 = (Keyword)cSECEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMINEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMINMinKeyword_1_0 = (Keyword)cMINEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMSEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMSMsKeyword_2_0 = (Keyword)cMSEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum TimeUnit:
		//    SEC='sec' | MIN='min' | MS='ms';
		public EnumRule getRule() { return rule; }
		
		//SEC='sec' | MIN='min' | MS='ms'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SEC='sec'
		public EnumLiteralDeclaration getSECEnumLiteralDeclaration_0() { return cSECEnumLiteralDeclaration_0; }
		
		//'sec'
		public Keyword getSECSecKeyword_0_0() { return cSECSecKeyword_0_0; }
		
		//MIN='min'
		public EnumLiteralDeclaration getMINEnumLiteralDeclaration_1() { return cMINEnumLiteralDeclaration_1; }
		
		//'min'
		public Keyword getMINMinKeyword_1_0() { return cMINMinKeyword_1_0; }
		
		//MS='ms'
		public EnumLiteralDeclaration getMSEnumLiteralDeclaration_2() { return cMSEnumLiteralDeclaration_2; }
		
		//'ms'
		public Keyword getMSMsKeyword_2_0() { return cMSMsKeyword_2_0; }
	}
	
	private final SystemElements pSystem;
	private final BrokerElements pBroker;
	private final NodeElements pNode;
	private final TopicElements pTopic;
	private final SensorElements pSensor;
	private final SampleRateElements pSampleRate;
	private final NumExprElements pNumExpr;
	private final NumMulElements pNumMul;
	private final NumAtomElements pNumAtom;
	private final TriggerElements pTrigger;
	private final TriggerConditionElements pTriggerCondition;
	private final TriggerActionElements pTriggerAction;
	private final PublishFieldElements pPublishField;
	private final ActuatorElements pActuator;
	private final OnMessageElements pOnMessage;
	private final CoordinatorElements pCoordinator;
	private final RuleElements pRule;
	private final RuleConditionElements pRuleCondition;
	private final BoolOrElements pBoolOr;
	private final BoolAndElements pBoolAnd;
	private final BoolNotElements pBoolNot;
	private final BoolAtomElements pBoolAtom;
	private final RuleActionElements pRuleAction;
	private final SensorTypeElements eSensorType;
	private final ActuatorTypeElements eActuatorType;
	private final QoSElements eQoS;
	private final OperatorElements eOperator;
	private final StateElements eState;
	private final TimeUnitElements eTimeUnit;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ElixirOfThingsGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSystem = new SystemElements();
		this.pBroker = new BrokerElements();
		this.pNode = new NodeElements();
		this.pTopic = new TopicElements();
		this.pSensor = new SensorElements();
		this.pSampleRate = new SampleRateElements();
		this.pNumExpr = new NumExprElements();
		this.pNumMul = new NumMulElements();
		this.pNumAtom = new NumAtomElements();
		this.pTrigger = new TriggerElements();
		this.pTriggerCondition = new TriggerConditionElements();
		this.pTriggerAction = new TriggerActionElements();
		this.pPublishField = new PublishFieldElements();
		this.pActuator = new ActuatorElements();
		this.pOnMessage = new OnMessageElements();
		this.pCoordinator = new CoordinatorElements();
		this.pRule = new RuleElements();
		this.pRuleCondition = new RuleConditionElements();
		this.pBoolOr = new BoolOrElements();
		this.pBoolAnd = new BoolAndElements();
		this.pBoolNot = new BoolNotElements();
		this.pBoolAtom = new BoolAtomElements();
		this.pRuleAction = new RuleActionElements();
		this.eSensorType = new SensorTypeElements();
		this.eActuatorType = new ActuatorTypeElements();
		this.eQoS = new QoSElements();
		this.eOperator = new OperatorElements();
		this.eState = new StateElements();
		this.eTimeUnit = new TimeUnitElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("elixir.of.things.ElixirOfThings".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//System:
	//    'system' name=ID '{'
	//        broker=Broker
	//        nodes+=Node+
	//        topics+=Topic*
	//        (sensors+=Sensor | actuators+=Actuator | coordinators+=Coordinator)*
	//    '}';
	public SystemElements getSystemAccess() {
		return pSystem;
	}
	
	public ParserRule getSystemRule() {
		return getSystemAccess().getRule();
	}
	
	//Broker:
	//    'broker:' host=STRING 'port:' port=INT;
	public BrokerElements getBrokerAccess() {
		return pBroker;
	}
	
	public ParserRule getBrokerRule() {
		return getBrokerAccess().getRule();
	}
	
	//Node:
	//    'node' name=ID;
	public NodeElements getNodeAccess() {
		return pNode;
	}
	
	public ParserRule getNodeRule() {
		return getNodeAccess().getRule();
	}
	
	//Topic:
	//    'topic' name=ID '=' '(' topicString=STRING ',' qos=QoS ')';
	public TopicElements getTopicAccess() {
		return pTopic;
	}
	
	public ParserRule getTopicRule() {
		return getTopicAccess().getRule();
	}
	
	//Sensor:
	//    'sensor' name=ID '{'
	//        'type:' type=SensorType
	//        'gpioPin:' gpioPin=INT
	//        'sampleRate:' sampleRate=SampleRate
	//        'deployedOn:' deployedOn=[Node]
	//        triggers+=Trigger*
	//    '}';
	public SensorElements getSensorAccess() {
		return pSensor;
	}
	
	public ParserRule getSensorRule() {
		return getSensorAccess().getRule();
	}
	
	//SampleRate:
	//    value=NumExpr unit=TimeUnit;
	public SampleRateElements getSampleRateAccess() {
		return pSampleRate;
	}
	
	public ParserRule getSampleRateRule() {
		return getSampleRateAccess().getRule();
	}
	
	//NumExpr returns NumExpr:
	//    NumMul (
	//        ({NumAddExpr.left=current} '+' | {NumSubExpr.left=current} '-')
	//        right=NumMul
	//    )*;
	public NumExprElements getNumExprAccess() {
		return pNumExpr;
	}
	
	public ParserRule getNumExprRule() {
		return getNumExprAccess().getRule();
	}
	
	//NumMul returns NumExpr:
	//    NumAtom (
	//        ({NumMulExpr.left=current} '*' | {NumDivExpr.left=current} '/')
	//        right=NumAtom
	//    )*;
	public NumMulElements getNumMulAccess() {
		return pNumMul;
	}
	
	public ParserRule getNumMulRule() {
		return getNumMulAccess().getRule();
	}
	
	//NumAtom returns NumExpr:
	//    {NumLiteral} value=INT |
	//    '(' NumExpr ')';
	public NumAtomElements getNumAtomAccess() {
		return pNumAtom;
	}
	
	public ParserRule getNumAtomRule() {
		return getNumAtomAccess().getRule();
	}
	
	//Trigger:
	//    'trigger' name=ID '{'
	//        condition=TriggerCondition
	//        actions+=TriggerAction+
	//    '}';
	public TriggerElements getTriggerAccess() {
		return pTrigger;
	}
	
	public ParserRule getTriggerRule() {
		return getTriggerAccess().getRule();
	}
	
	//TriggerCondition:
	//    'when' 'value' operator=Operator right=NumExpr ':';
	public TriggerConditionElements getTriggerConditionAccess() {
		return pTriggerCondition;
	}
	
	public ParserRule getTriggerConditionRule() {
		return getTriggerConditionAccess().getRule();
	}
	
	//TriggerAction:
	//    'publish' topic=[Topic] ':' '{' fields+=PublishField (',' fields+=PublishField)* '}';
	public TriggerActionElements getTriggerActionAccess() {
		return pTriggerAction;
	}
	
	public ParserRule getTriggerActionRule() {
		return getTriggerActionAccess().getRule();
	}
	
	//PublishField:
	//    {ValueField}     'value'     |
	//    {TimestampField} 'timestamp';
	public PublishFieldElements getPublishFieldAccess() {
		return pPublishField;
	}
	
	public ParserRule getPublishFieldRule() {
		return getPublishFieldAccess().getRule();
	}
	
	//Actuator:
	//    'actuator' name=ID '{'
	//        'type:' type=ActuatorType
	//        'gpioPin:' gpioPin=INT
	//        'deployedOn:' deployedOn=[Node]
	//        'subscribeTo:' subscribeTo+=[Topic] (',' subscribeTo+=[Topic])*
	//        messages+=OnMessage*
	//    '}';
	public ActuatorElements getActuatorAccess() {
		return pActuator;
	}
	
	public ParserRule getActuatorRule() {
		return getActuatorAccess().getRule();
	}
	
	//OnMessage:
	//    'on' 'message' 'from' topic=[Topic] ':'
	//        'turn' state=State ('for' duration=SampleRate)?;
	public OnMessageElements getOnMessageAccess() {
		return pOnMessage;
	}
	
	public ParserRule getOnMessageRule() {
		return getOnMessageAccess().getRule();
	}
	
	//Coordinator:
	//    'coordinator' name=ID '{'
	//        'deployedOn:' deployedOn=[Node]
	//        'subscribeTo:' subscribeTo+=[Topic] (',' subscribeTo+=[Topic])*
	//        rules+=Rule*
	//    '}';
	public CoordinatorElements getCoordinatorAccess() {
		return pCoordinator;
	}
	
	public ParserRule getCoordinatorRule() {
		return getCoordinatorAccess().getRule();
	}
	
	//Rule:
	//    'rule' name=ID '{'
	//        condition=RuleCondition
	//        actions+=RuleAction+
	//    '}';
	public RuleElements getRuleAccess() {
		return pRule;
	}
	
	public ParserRule getRuleRule() {
		return getRuleAccess().getRule();
	}
	
	//RuleCondition:
	//    'when' expression=BoolOr ':';
	public RuleConditionElements getRuleConditionAccess() {
		return pRuleCondition;
	}
	
	public ParserRule getRuleConditionRule() {
		return getRuleConditionAccess().getRule();
	}
	
	//BoolOr returns BoolExpr:
	//    BoolAnd ({BoolOrExpr.left=current} 'or' right=BoolAnd)*;
	public BoolOrElements getBoolOrAccess() {
		return pBoolOr;
	}
	
	public ParserRule getBoolOrRule() {
		return getBoolOrAccess().getRule();
	}
	
	//BoolAnd returns BoolExpr:
	//    BoolNot ({BoolAndExpr.left=current} 'and' right=BoolNot)*;
	public BoolAndElements getBoolAndAccess() {
		return pBoolAnd;
	}
	
	public ParserRule getBoolAndRule() {
		return getBoolAndAccess().getRule();
	}
	
	//BoolNot returns BoolExpr:
	//    {BoolNotExpr} 'not' operand=BoolAtom |
	//    BoolAtom;
	public BoolNotElements getBoolNotAccess() {
		return pBoolNot;
	}
	
	public ParserRule getBoolNotRule() {
		return getBoolNotAccess().getRule();
	}
	
	//BoolAtom returns BoolExpr:
	//    {TopicRef} topic=[Topic] |
	//    '(' BoolOr ')';
	public BoolAtomElements getBoolAtomAccess() {
		return pBoolAtom;
	}
	
	public ParserRule getBoolAtomRule() {
		return getBoolAtomAccess().getRule();
	}
	
	//RuleAction:
	//    'publish' topic=[Topic] ':' '{' ('message:' message=STRING)? '}';
	public RuleActionElements getRuleActionAccess() {
		return pRuleAction;
	}
	
	public ParserRule getRuleActionRule() {
		return getRuleActionAccess().getRule();
	}
	
	//enum SensorType:
	//    TEMP_DS18B20 | TEMP_DHT22 | HUMIDITY | MOTION_PIR | LIGHT | DISTANCE;
	public SensorTypeElements getSensorTypeAccess() {
		return eSensorType;
	}
	
	public EnumRule getSensorTypeRule() {
		return getSensorTypeAccess().getRule();
	}
	
	//enum ActuatorType:
	//    RELAY | LED | BUZZER | SERVO;
	public ActuatorTypeElements getActuatorTypeAccess() {
		return eActuatorType;
	}
	
	public EnumRule getActuatorTypeRule() {
		return getActuatorTypeAccess().getRule();
	}
	
	//enum QoS:
	//    AT_MOST_ONCE | AT_LEAST_ONCE | EXACTLY_ONCE;
	public QoSElements getQoSAccess() {
		return eQoS;
	}
	
	public EnumRule getQoSRule() {
		return getQoSAccess().getRule();
	}
	
	//enum Operator:
	//    GREATER_THAN='>' | LESS_THAN='<' | GREATER_EQ='>=' | LESS_EQ='<=' | EQUALS='==';
	public OperatorElements getOperatorAccess() {
		return eOperator;
	}
	
	public EnumRule getOperatorRule() {
		return getOperatorAccess().getRule();
	}
	
	//enum State:
	//    ON | OFF;
	public StateElements getStateAccess() {
		return eState;
	}
	
	public EnumRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//enum TimeUnit:
	//    SEC='sec' | MIN='min' | MS='ms';
	public TimeUnitElements getTimeUnitAccess() {
		return eTimeUnit;
	}
	
	public EnumRule getTimeUnitRule() {
		return getTimeUnitAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
