/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings.impl;

import elixir.of.things.elixirOfThings.Duration;
import elixir.of.things.elixirOfThings.ElixirOfThingsPackage;
import elixir.of.things.elixirOfThings.Node;
import elixir.of.things.elixirOfThings.Sensor;
import elixir.of.things.elixirOfThings.SensorType;
import elixir.of.things.elixirOfThings.Trigger;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link elixir.of.things.elixirOfThings.impl.SensorImpl#getName <em>Name</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.impl.SensorImpl#getType <em>Type</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.impl.SensorImpl#getGpioPin <em>Gpio Pin</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.impl.SensorImpl#getSampleRate <em>Sample Rate</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.impl.SensorImpl#getDeployedOn <em>Deployed On</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.impl.SensorImpl#getTriggers <em>Triggers</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SensorImpl extends MinimalEObjectImpl.Container implements Sensor
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final SensorType TYPE_EDEFAULT = SensorType.TEMPERATURE;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected SensorType type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getGpioPin() <em>Gpio Pin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGpioPin()
   * @generated
   * @ordered
   */
  protected static final int GPIO_PIN_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getGpioPin() <em>Gpio Pin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGpioPin()
   * @generated
   * @ordered
   */
  protected int gpioPin = GPIO_PIN_EDEFAULT;

  /**
   * The cached value of the '{@link #getSampleRate() <em>Sample Rate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSampleRate()
   * @generated
   * @ordered
   */
  protected Duration sampleRate;

  /**
   * The cached value of the '{@link #getDeployedOn() <em>Deployed On</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeployedOn()
   * @generated
   * @ordered
   */
  protected Node deployedOn;

  /**
   * The cached value of the '{@link #getTriggers() <em>Triggers</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTriggers()
   * @generated
   * @ordered
   */
  protected EList<Trigger> triggers;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SensorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ElixirOfThingsPackage.Literals.SENSOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ElixirOfThingsPackage.SENSOR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SensorType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(SensorType newType)
  {
    SensorType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ElixirOfThingsPackage.SENSOR__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getGpioPin()
  {
    return gpioPin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGpioPin(int newGpioPin)
  {
    int oldGpioPin = gpioPin;
    gpioPin = newGpioPin;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ElixirOfThingsPackage.SENSOR__GPIO_PIN, oldGpioPin, gpioPin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Duration getSampleRate()
  {
    return sampleRate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSampleRate(Duration newSampleRate, NotificationChain msgs)
  {
    Duration oldSampleRate = sampleRate;
    sampleRate = newSampleRate;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ElixirOfThingsPackage.SENSOR__SAMPLE_RATE, oldSampleRate, newSampleRate);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSampleRate(Duration newSampleRate)
  {
    if (newSampleRate != sampleRate)
    {
      NotificationChain msgs = null;
      if (sampleRate != null)
        msgs = ((InternalEObject)sampleRate).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ElixirOfThingsPackage.SENSOR__SAMPLE_RATE, null, msgs);
      if (newSampleRate != null)
        msgs = ((InternalEObject)newSampleRate).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ElixirOfThingsPackage.SENSOR__SAMPLE_RATE, null, msgs);
      msgs = basicSetSampleRate(newSampleRate, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ElixirOfThingsPackage.SENSOR__SAMPLE_RATE, newSampleRate, newSampleRate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Node getDeployedOn()
  {
    if (deployedOn != null && deployedOn.eIsProxy())
    {
      InternalEObject oldDeployedOn = (InternalEObject)deployedOn;
      deployedOn = (Node)eResolveProxy(oldDeployedOn);
      if (deployedOn != oldDeployedOn)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ElixirOfThingsPackage.SENSOR__DEPLOYED_ON, oldDeployedOn, deployedOn));
      }
    }
    return deployedOn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Node basicGetDeployedOn()
  {
    return deployedOn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeployedOn(Node newDeployedOn)
  {
    Node oldDeployedOn = deployedOn;
    deployedOn = newDeployedOn;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ElixirOfThingsPackage.SENSOR__DEPLOYED_ON, oldDeployedOn, deployedOn));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Trigger> getTriggers()
  {
    if (triggers == null)
    {
      triggers = new EObjectContainmentEList<Trigger>(Trigger.class, this, ElixirOfThingsPackage.SENSOR__TRIGGERS);
    }
    return triggers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ElixirOfThingsPackage.SENSOR__SAMPLE_RATE:
        return basicSetSampleRate(null, msgs);
      case ElixirOfThingsPackage.SENSOR__TRIGGERS:
        return ((InternalEList<?>)getTriggers()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ElixirOfThingsPackage.SENSOR__NAME:
        return getName();
      case ElixirOfThingsPackage.SENSOR__TYPE:
        return getType();
      case ElixirOfThingsPackage.SENSOR__GPIO_PIN:
        return getGpioPin();
      case ElixirOfThingsPackage.SENSOR__SAMPLE_RATE:
        return getSampleRate();
      case ElixirOfThingsPackage.SENSOR__DEPLOYED_ON:
        if (resolve) return getDeployedOn();
        return basicGetDeployedOn();
      case ElixirOfThingsPackage.SENSOR__TRIGGERS:
        return getTriggers();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ElixirOfThingsPackage.SENSOR__NAME:
        setName((String)newValue);
        return;
      case ElixirOfThingsPackage.SENSOR__TYPE:
        setType((SensorType)newValue);
        return;
      case ElixirOfThingsPackage.SENSOR__GPIO_PIN:
        setGpioPin((Integer)newValue);
        return;
      case ElixirOfThingsPackage.SENSOR__SAMPLE_RATE:
        setSampleRate((Duration)newValue);
        return;
      case ElixirOfThingsPackage.SENSOR__DEPLOYED_ON:
        setDeployedOn((Node)newValue);
        return;
      case ElixirOfThingsPackage.SENSOR__TRIGGERS:
        getTriggers().clear();
        getTriggers().addAll((Collection<? extends Trigger>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ElixirOfThingsPackage.SENSOR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ElixirOfThingsPackage.SENSOR__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case ElixirOfThingsPackage.SENSOR__GPIO_PIN:
        setGpioPin(GPIO_PIN_EDEFAULT);
        return;
      case ElixirOfThingsPackage.SENSOR__SAMPLE_RATE:
        setSampleRate((Duration)null);
        return;
      case ElixirOfThingsPackage.SENSOR__DEPLOYED_ON:
        setDeployedOn((Node)null);
        return;
      case ElixirOfThingsPackage.SENSOR__TRIGGERS:
        getTriggers().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ElixirOfThingsPackage.SENSOR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ElixirOfThingsPackage.SENSOR__TYPE:
        return type != TYPE_EDEFAULT;
      case ElixirOfThingsPackage.SENSOR__GPIO_PIN:
        return gpioPin != GPIO_PIN_EDEFAULT;
      case ElixirOfThingsPackage.SENSOR__SAMPLE_RATE:
        return sampleRate != null;
      case ElixirOfThingsPackage.SENSOR__DEPLOYED_ON:
        return deployedOn != null;
      case ElixirOfThingsPackage.SENSOR__TRIGGERS:
        return triggers != null && !triggers.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", type: ");
    result.append(type);
    result.append(", gpioPin: ");
    result.append(gpioPin);
    result.append(')');
    return result.toString();
  }

} //SensorImpl
