/*
 * generated by Xtext 2.41.0
 */
package elixir.of.things.serializer;

import com.google.inject.Inject;
import elixir.of.things.elixirOfThings.Actuator;
import elixir.of.things.elixirOfThings.Broker;
import elixir.of.things.elixirOfThings.Coordinator;
import elixir.of.things.elixirOfThings.Duration;
import elixir.of.things.elixirOfThings.ElixirOfThingsPackage;
import elixir.of.things.elixirOfThings.Node;
import elixir.of.things.elixirOfThings.OnMessage;
import elixir.of.things.elixirOfThings.Rule;
import elixir.of.things.elixirOfThings.RuleAction;
import elixir.of.things.elixirOfThings.RuleCondition;
import elixir.of.things.elixirOfThings.Sensor;
import elixir.of.things.elixirOfThings.TimestampField;
import elixir.of.things.elixirOfThings.Topic;
import elixir.of.things.elixirOfThings.Trigger;
import elixir.of.things.elixirOfThings.TriggerAction;
import elixir.of.things.elixirOfThings.TriggerCondition;
import elixir.of.things.elixirOfThings.ValueField;
import elixir.of.things.services.ElixirOfThingsGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class ElixirOfThingsSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ElixirOfThingsGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ElixirOfThingsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ElixirOfThingsPackage.ACTUATOR:
				sequence_Actuator(context, (Actuator) semanticObject); 
				return; 
			case ElixirOfThingsPackage.BROKER:
				sequence_Broker(context, (Broker) semanticObject); 
				return; 
			case ElixirOfThingsPackage.COORDINATOR:
				sequence_Coordinator(context, (Coordinator) semanticObject); 
				return; 
			case ElixirOfThingsPackage.DURATION:
				sequence_Duration(context, (Duration) semanticObject); 
				return; 
			case ElixirOfThingsPackage.NODE:
				sequence_Node(context, (Node) semanticObject); 
				return; 
			case ElixirOfThingsPackage.ON_MESSAGE:
				sequence_OnMessage(context, (OnMessage) semanticObject); 
				return; 
			case ElixirOfThingsPackage.RULE:
				sequence_Rule(context, (Rule) semanticObject); 
				return; 
			case ElixirOfThingsPackage.RULE_ACTION:
				sequence_RuleAction(context, (RuleAction) semanticObject); 
				return; 
			case ElixirOfThingsPackage.RULE_CONDITION:
				sequence_RuleCondition(context, (RuleCondition) semanticObject); 
				return; 
			case ElixirOfThingsPackage.SENSOR:
				sequence_Sensor(context, (Sensor) semanticObject); 
				return; 
			case ElixirOfThingsPackage.SYSTEM:
				sequence_System(context, (elixir.of.things.elixirOfThings.System) semanticObject); 
				return; 
			case ElixirOfThingsPackage.TIMESTAMP_FIELD:
				sequence_PublishField(context, (TimestampField) semanticObject); 
				return; 
			case ElixirOfThingsPackage.TOPIC:
				sequence_Topic(context, (Topic) semanticObject); 
				return; 
			case ElixirOfThingsPackage.TRIGGER:
				sequence_Trigger(context, (Trigger) semanticObject); 
				return; 
			case ElixirOfThingsPackage.TRIGGER_ACTION:
				sequence_TriggerAction(context, (TriggerAction) semanticObject); 
				return; 
			case ElixirOfThingsPackage.TRIGGER_CONDITION:
				sequence_TriggerCondition(context, (TriggerCondition) semanticObject); 
				return; 
			case ElixirOfThingsPackage.VALUE_FIELD:
				sequence_PublishField(context, (ValueField) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Actuator returns Actuator
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         type=ActuatorType 
	 *         gpioPin=INT 
	 *         deployedOn=[Node|ID] 
	 *         subscribeTo+=[Topic|ID] 
	 *         subscribeTo+=[Topic|ID]* 
	 *         messages+=OnMessage*
	 *     )
	 * </pre>
	 */
	protected void sequence_Actuator(ISerializationContext context, Actuator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Broker returns Broker
	 *
	 * Constraint:
	 *     (host=STRING port=INT)
	 * </pre>
	 */
	protected void sequence_Broker(ISerializationContext context, Broker semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ElixirOfThingsPackage.Literals.BROKER__HOST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ElixirOfThingsPackage.Literals.BROKER__HOST));
			if (transientValues.isValueTransient(semanticObject, ElixirOfThingsPackage.Literals.BROKER__PORT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ElixirOfThingsPackage.Literals.BROKER__PORT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBrokerAccess().getHostSTRINGTerminalRuleCall_1_0(), semanticObject.getHost());
		feeder.accept(grammarAccess.getBrokerAccess().getPortINTTerminalRuleCall_3_0(), semanticObject.getPort());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Coordinator returns Coordinator
	 *
	 * Constraint:
	 *     (name=ID deployedOn=[Node|ID] subscribeTo+=[Topic|ID] subscribeTo+=[Topic|ID]* rules+=Rule*)
	 * </pre>
	 */
	protected void sequence_Coordinator(ISerializationContext context, Coordinator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Duration returns Duration
	 *
	 * Constraint:
	 *     (value=INT unit=TimeUnit)
	 * </pre>
	 */
	protected void sequence_Duration(ISerializationContext context, Duration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ElixirOfThingsPackage.Literals.DURATION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ElixirOfThingsPackage.Literals.DURATION__VALUE));
			if (transientValues.isValueTransient(semanticObject, ElixirOfThingsPackage.Literals.DURATION__UNIT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ElixirOfThingsPackage.Literals.DURATION__UNIT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDurationAccess().getValueINTTerminalRuleCall_0_0(), semanticObject.getValue());
		feeder.accept(grammarAccess.getDurationAccess().getUnitTimeUnitEnumRuleCall_1_0(), semanticObject.getUnit());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns Node
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_Node(ISerializationContext context, Node semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ElixirOfThingsPackage.Literals.NODE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ElixirOfThingsPackage.Literals.NODE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNodeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     OnMessage returns OnMessage
	 *
	 * Constraint:
	 *     (topic=[Topic|ID] state=State duration=Duration?)
	 * </pre>
	 */
	protected void sequence_OnMessage(ISerializationContext context, OnMessage semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PublishField returns TimestampField
	 *
	 * Constraint:
	 *     {TimestampField}
	 * </pre>
	 */
	protected void sequence_PublishField(ISerializationContext context, TimestampField semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PublishField returns ValueField
	 *
	 * Constraint:
	 *     {ValueField}
	 * </pre>
	 */
	protected void sequence_PublishField(ISerializationContext context, ValueField semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RuleAction returns RuleAction
	 *
	 * Constraint:
	 *     (topic=[Topic|ID] message=STRING?)
	 * </pre>
	 */
	protected void sequence_RuleAction(ISerializationContext context, RuleAction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RuleCondition returns RuleCondition
	 *
	 * Constraint:
	 *     (topics+=[Topic|ID] (operators+=LogicalOp topics+=[Topic|ID])*)
	 * </pre>
	 */
	protected void sequence_RuleCondition(ISerializationContext context, RuleCondition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Rule returns Rule
	 *
	 * Constraint:
	 *     (name=ID condition=RuleCondition actions+=RuleAction+)
	 * </pre>
	 */
	protected void sequence_Rule(ISerializationContext context, Rule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Sensor returns Sensor
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         type=SensorType 
	 *         gpioPin=INT 
	 *         sampleRate=Duration 
	 *         deployedOn=[Node|ID] 
	 *         triggers+=Trigger*
	 *     )
	 * </pre>
	 */
	protected void sequence_Sensor(ISerializationContext context, Sensor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     System returns System
	 *
	 * Constraint:
	 *     (name=ID broker=Broker nodes+=Node+ topics+=Topic* (sensors+=Sensor | actuators+=Actuator | coordinators+=Coordinator)*)
	 * </pre>
	 */
	protected void sequence_System(ISerializationContext context, elixir.of.things.elixirOfThings.System semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Topic returns Topic
	 *
	 * Constraint:
	 *     (name=ID topicString=STRING qos=QoS)
	 * </pre>
	 */
	protected void sequence_Topic(ISerializationContext context, Topic semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ElixirOfThingsPackage.Literals.TOPIC__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ElixirOfThingsPackage.Literals.TOPIC__NAME));
			if (transientValues.isValueTransient(semanticObject, ElixirOfThingsPackage.Literals.TOPIC__TOPIC_STRING) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ElixirOfThingsPackage.Literals.TOPIC__TOPIC_STRING));
			if (transientValues.isValueTransient(semanticObject, ElixirOfThingsPackage.Literals.TOPIC__QOS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ElixirOfThingsPackage.Literals.TOPIC__QOS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTopicAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getTopicAccess().getTopicStringSTRINGTerminalRuleCall_4_0(), semanticObject.getTopicString());
		feeder.accept(grammarAccess.getTopicAccess().getQosQoSEnumRuleCall_6_0(), semanticObject.getQos());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TriggerAction returns TriggerAction
	 *
	 * Constraint:
	 *     (topic=[Topic|ID] fields+=PublishField fields+=PublishField*)
	 * </pre>
	 */
	protected void sequence_TriggerAction(ISerializationContext context, TriggerAction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TriggerCondition returns TriggerCondition
	 *
	 * Constraint:
	 *     (operator=Operator right=INT)
	 * </pre>
	 */
	protected void sequence_TriggerCondition(ISerializationContext context, TriggerCondition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ElixirOfThingsPackage.Literals.TRIGGER_CONDITION__OPERATOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ElixirOfThingsPackage.Literals.TRIGGER_CONDITION__OPERATOR));
			if (transientValues.isValueTransient(semanticObject, ElixirOfThingsPackage.Literals.TRIGGER_CONDITION__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ElixirOfThingsPackage.Literals.TRIGGER_CONDITION__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTriggerConditionAccess().getOperatorOperatorEnumRuleCall_2_0(), semanticObject.getOperator());
		feeder.accept(grammarAccess.getTriggerConditionAccess().getRightINTTerminalRuleCall_3_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Trigger returns Trigger
	 *
	 * Constraint:
	 *     (name=ID condition=TriggerCondition actions+=TriggerAction+)
	 * </pre>
	 */
	protected void sequence_Trigger(ISerializationContext context, Trigger semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
