/*
 * generated by Xtext 2.41.0
 */
package elixir.of.things.ide;


/**
 * Use this class to register ide components.
 */
public class ElixirOfThingsIdeModule extends AbstractElixirOfThingsIdeModule {
}
