/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actuator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link elixir.of.things.elixirOfThings.Actuator#getName <em>Name</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.Actuator#getType <em>Type</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.Actuator#getGpioPin <em>Gpio Pin</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.Actuator#getDeployedOn <em>Deployed On</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.Actuator#getSubscribeTo <em>Subscribe To</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.Actuator#getMessages <em>Messages</em>}</li>
 * </ul>
 *
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getActuator()
 * @model
 * @generated
 */
public interface Actuator extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getActuator_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.Actuator#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link elixir.of.things.elixirOfThings.ActuatorType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see elixir.of.things.elixirOfThings.ActuatorType
   * @see #setType(ActuatorType)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getActuator_Type()
   * @model
   * @generated
   */
  ActuatorType getType();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.Actuator#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see elixir.of.things.elixirOfThings.ActuatorType
   * @see #getType()
   * @generated
   */
  void setType(ActuatorType value);

  /**
   * Returns the value of the '<em><b>Gpio Pin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gpio Pin</em>' attribute.
   * @see #setGpioPin(int)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getActuator_GpioPin()
   * @model
   * @generated
   */
  int getGpioPin();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.Actuator#getGpioPin <em>Gpio Pin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gpio Pin</em>' attribute.
   * @see #getGpioPin()
   * @generated
   */
  void setGpioPin(int value);

  /**
   * Returns the value of the '<em><b>Deployed On</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deployed On</em>' reference.
   * @see #setDeployedOn(Node)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getActuator_DeployedOn()
   * @model
   * @generated
   */
  Node getDeployedOn();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.Actuator#getDeployedOn <em>Deployed On</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Deployed On</em>' reference.
   * @see #getDeployedOn()
   * @generated
   */
  void setDeployedOn(Node value);

  /**
   * Returns the value of the '<em><b>Subscribe To</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subscribe To</em>' attribute list.
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getActuator_SubscribeTo()
   * @model unique="false"
   * @generated
   */
  EList<String> getSubscribeTo();

  /**
   * Returns the value of the '<em><b>Messages</b></em>' containment reference list.
   * The list contents are of type {@link elixir.of.things.elixirOfThings.OnMessage}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Messages</em>' containment reference list.
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getActuator_Messages()
   * @model containment="true"
   * @generated
   */
  EList<OnMessage> getMessages();

} // Actuator
