/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Actuator Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getActuatorType()
 * @model
 * @generated
 */
public enum ActuatorType implements Enumerator
{
  /**
   * The '<em><b>RELAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RELAY_VALUE
   * @generated
   * @ordered
   */
  RELAY(0, "RELAY", "RELAY"),

  /**
   * The '<em><b>LED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LED_VALUE
   * @generated
   * @ordered
   */
  LED(1, "LED", "LED"),

  /**
   * The '<em><b>BUZZER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUZZER_VALUE
   * @generated
   * @ordered
   */
  BUZZER(2, "BUZZER", "BUZZER"),

  /**
   * The '<em><b>SERVO</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SERVO_VALUE
   * @generated
   * @ordered
   */
  SERVO(3, "SERVO", "SERVO");

  /**
   * The '<em><b>RELAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RELAY
   * @model
   * @generated
   * @ordered
   */
  public static final int RELAY_VALUE = 0;

  /**
   * The '<em><b>LED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LED
   * @model
   * @generated
   * @ordered
   */
  public static final int LED_VALUE = 1;

  /**
   * The '<em><b>BUZZER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUZZER
   * @model
   * @generated
   * @ordered
   */
  public static final int BUZZER_VALUE = 2;

  /**
   * The '<em><b>SERVO</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SERVO
   * @model
   * @generated
   * @ordered
   */
  public static final int SERVO_VALUE = 3;

  /**
   * An array of all the '<em><b>Actuator Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ActuatorType[] VALUES_ARRAY =
    new ActuatorType[]
    {
      RELAY,
      LED,
      BUZZER,
      SERVO,
    };

  /**
   * A public read-only list of all the '<em><b>Actuator Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ActuatorType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Actuator Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ActuatorType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ActuatorType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Actuator Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ActuatorType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ActuatorType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Actuator Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ActuatorType get(int value)
  {
    switch (value)
    {
      case RELAY_VALUE: return RELAY;
      case LED_VALUE: return LED;
      case BUZZER_VALUE: return BUZZER;
      case SERVO_VALUE: return SERVO;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ActuatorType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ActuatorType
