/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Duration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link elixir.of.things.elixirOfThings.Duration#getValue <em>Value</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.Duration#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getDuration()
 * @model
 * @generated
 */
public interface Duration extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getDuration_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.Duration#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * The literals are from the enumeration {@link elixir.of.things.elixirOfThings.TimeUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see elixir.of.things.elixirOfThings.TimeUnit
   * @see #setUnit(TimeUnit)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getDuration_Unit()
   * @model
   * @generated
   */
  TimeUnit getUnit();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.Duration#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see elixir.of.things.elixirOfThings.TimeUnit
   * @see #getUnit()
   * @generated
   */
  void setUnit(TimeUnit value);

} // Duration
