/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsFactory
 * @model kind="package"
 * @generated
 */
public interface ElixirOfThingsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "elixirOfThings";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.of.elixir/things/ElixirOfThings";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "elixirOfThings";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ElixirOfThingsPackage eINSTANCE = elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl.init();

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.SystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.SystemImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getSystem()
   * @generated
   */
  int SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__NAME = 0;

  /**
   * The feature id for the '<em><b>Broker</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__BROKER = 1;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__NODES = 2;

  /**
   * The feature id for the '<em><b>Topics</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__TOPICS = 3;

  /**
   * The feature id for the '<em><b>Sensors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__SENSORS = 4;

  /**
   * The feature id for the '<em><b>Actuators</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__ACTUATORS = 5;

  /**
   * The feature id for the '<em><b>Coordinators</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__COORDINATORS = 6;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.BrokerImpl <em>Broker</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.BrokerImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getBroker()
   * @generated
   */
  int BROKER = 1;

  /**
   * The feature id for the '<em><b>Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROKER__HOST = 0;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROKER__PORT = 1;

  /**
   * The number of structural features of the '<em>Broker</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROKER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.NodeImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getNode()
   * @generated
   */
  int NODE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NAME = 0;

  /**
   * The feature id for the '<em><b>Ip Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__IP_ADDRESS = 1;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.TopicImpl <em>Topic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.TopicImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTopic()
   * @generated
   */
  int TOPIC = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC__NAME = 0;

  /**
   * The feature id for the '<em><b>Qos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC__QOS = 1;

  /**
   * The number of structural features of the '<em>Topic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.SensorImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__TYPE = 1;

  /**
   * The feature id for the '<em><b>Gpio Pin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__GPIO_PIN = 2;

  /**
   * The feature id for the '<em><b>Sample Rate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__SAMPLE_RATE = 3;

  /**
   * The feature id for the '<em><b>Deployed On</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__DEPLOYED_ON = 4;

  /**
   * The feature id for the '<em><b>Triggers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__TRIGGERS = 5;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.TriggerImpl <em>Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.TriggerImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTrigger()
   * @generated
   */
  int TRIGGER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__NAME = 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__CONDITION = 1;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__ACTIONS = 2;

  /**
   * The number of structural features of the '<em>Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.TriggerConditionImpl <em>Trigger Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.TriggerConditionImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTriggerCondition()
   * @generated
   */
  int TRIGGER_CONDITION = 6;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_CONDITION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_CONDITION__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_CONDITION__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Trigger Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_CONDITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.TriggerActionImpl <em>Trigger Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.TriggerActionImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTriggerAction()
   * @generated
   */
  int TRIGGER_ACTION = 7;

  /**
   * The feature id for the '<em><b>Topic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_ACTION__TOPIC = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_ACTION__FIELDS = 1;

  /**
   * The number of structural features of the '<em>Trigger Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_ACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.ActuatorImpl <em>Actuator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.ActuatorImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getActuator()
   * @generated
   */
  int ACTUATOR = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__TYPE = 1;

  /**
   * The feature id for the '<em><b>Gpio Pin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__GPIO_PIN = 2;

  /**
   * The feature id for the '<em><b>Deployed On</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__DEPLOYED_ON = 3;

  /**
   * The feature id for the '<em><b>Subscribe To</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__SUBSCRIBE_TO = 4;

  /**
   * The feature id for the '<em><b>Messages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__MESSAGES = 5;

  /**
   * The number of structural features of the '<em>Actuator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.OnMessageImpl <em>On Message</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.OnMessageImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getOnMessage()
   * @generated
   */
  int ON_MESSAGE = 9;

  /**
   * The feature id for the '<em><b>Topic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ON_MESSAGE__TOPIC = 0;

  /**
   * The feature id for the '<em><b>State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ON_MESSAGE__STATE = 1;

  /**
   * The feature id for the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ON_MESSAGE__DURATION = 2;

  /**
   * The number of structural features of the '<em>On Message</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ON_MESSAGE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.CoordinatorImpl <em>Coordinator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.CoordinatorImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getCoordinator()
   * @generated
   */
  int COORDINATOR = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Deployed On</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATOR__DEPLOYED_ON = 1;

  /**
   * The feature id for the '<em><b>Subscribe To</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATOR__SUBSCRIBE_TO = 2;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATOR__RULES = 3;

  /**
   * The number of structural features of the '<em>Coordinator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATOR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.RuleImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getRule()
   * @generated
   */
  int RULE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITION = 1;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ACTIONS = 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.RuleConditionImpl <em>Rule Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.RuleConditionImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getRuleCondition()
   * @generated
   */
  int RULE_CONDITION = 12;

  /**
   * The feature id for the '<em><b>Topics</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_CONDITION__TOPICS = 0;

  /**
   * The feature id for the '<em><b>Operators</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_CONDITION__OPERATORS = 1;

  /**
   * The number of structural features of the '<em>Rule Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_CONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.TopicPathImpl <em>Topic Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.TopicPathImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTopicPath()
   * @generated
   */
  int TOPIC_PATH = 13;

  /**
   * The feature id for the '<em><b>Segments</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC_PATH__SEGMENTS = 0;

  /**
   * The number of structural features of the '<em>Topic Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC_PATH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.RuleActionImpl <em>Rule Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.RuleActionImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getRuleAction()
   * @generated
   */
  int RULE_ACTION = 14;

  /**
   * The feature id for the '<em><b>Topic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_ACTION__TOPIC = 0;

  /**
   * The feature id for the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_ACTION__MESSAGE = 1;

  /**
   * The number of structural features of the '<em>Rule Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_ACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.DurationImpl <em>Duration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.DurationImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getDuration()
   * @generated
   */
  int DURATION = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DURATION__VALUE = 0;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DURATION__UNIT = 1;

  /**
   * The number of structural features of the '<em>Duration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DURATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.ExpressionImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 16;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.ValueExprImpl <em>Value Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.ValueExprImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getValueExpr()
   * @generated
   */
  int VALUE_EXPR = 17;

  /**
   * The number of structural features of the '<em>Value Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.TimestampExprImpl <em>Timestamp Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.TimestampExprImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTimestampExpr()
   * @generated
   */
  int TIMESTAMP_EXPR = 18;

  /**
   * The number of structural features of the '<em>Timestamp Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMESTAMP_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.LiteralIntImpl <em>Literal Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.LiteralIntImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getLiteralInt()
   * @generated
   */
  int LITERAL_INT = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_INT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Literal Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_INT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.impl.LiteralStringImpl <em>Literal String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.impl.LiteralStringImpl
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getLiteralString()
   * @generated
   */
  int LITERAL_STRING = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_STRING__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Literal String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_STRING_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.SensorType <em>Sensor Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.SensorType
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getSensorType()
   * @generated
   */
  int SENSOR_TYPE = 21;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.ActuatorType <em>Actuator Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.ActuatorType
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getActuatorType()
   * @generated
   */
  int ACTUATOR_TYPE = 22;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.QoS <em>Qo S</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.QoS
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getQoS()
   * @generated
   */
  int QO_S = 23;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.Operator <em>Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.Operator
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 24;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.LogicalOp <em>Logical Op</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.LogicalOp
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getLogicalOp()
   * @generated
   */
  int LOGICAL_OP = 25;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.State <em>State</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.State
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getState()
   * @generated
   */
  int STATE = 26;

  /**
   * The meta object id for the '{@link elixir.of.things.elixirOfThings.TimeUnit <em>Time Unit</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see elixir.of.things.elixirOfThings.TimeUnit
   * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTimeUnit()
   * @generated
   */
  int TIME_UNIT = 27;


  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.System <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see elixir.of.things.elixirOfThings.System
   * @generated
   */
  EClass getSystem();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.System#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see elixir.of.things.elixirOfThings.System#getName()
   * @see #getSystem()
   * @generated
   */
  EAttribute getSystem_Name();

  /**
   * Returns the meta object for the containment reference '{@link elixir.of.things.elixirOfThings.System#getBroker <em>Broker</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Broker</em>'.
   * @see elixir.of.things.elixirOfThings.System#getBroker()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Broker();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.System#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nodes</em>'.
   * @see elixir.of.things.elixirOfThings.System#getNodes()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Nodes();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.System#getTopics <em>Topics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Topics</em>'.
   * @see elixir.of.things.elixirOfThings.System#getTopics()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Topics();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.System#getSensors <em>Sensors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensors</em>'.
   * @see elixir.of.things.elixirOfThings.System#getSensors()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Sensors();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.System#getActuators <em>Actuators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actuators</em>'.
   * @see elixir.of.things.elixirOfThings.System#getActuators()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Actuators();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.System#getCoordinators <em>Coordinators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Coordinators</em>'.
   * @see elixir.of.things.elixirOfThings.System#getCoordinators()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Coordinators();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.Broker <em>Broker</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Broker</em>'.
   * @see elixir.of.things.elixirOfThings.Broker
   * @generated
   */
  EClass getBroker();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Broker#getHost <em>Host</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Host</em>'.
   * @see elixir.of.things.elixirOfThings.Broker#getHost()
   * @see #getBroker()
   * @generated
   */
  EAttribute getBroker_Host();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Broker#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see elixir.of.things.elixirOfThings.Broker#getPort()
   * @see #getBroker()
   * @generated
   */
  EAttribute getBroker_Port();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see elixir.of.things.elixirOfThings.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Node#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see elixir.of.things.elixirOfThings.Node#getName()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Name();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Node#getIpAddress <em>Ip Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip Address</em>'.
   * @see elixir.of.things.elixirOfThings.Node#getIpAddress()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_IpAddress();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.Topic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Topic</em>'.
   * @see elixir.of.things.elixirOfThings.Topic
   * @generated
   */
  EClass getTopic();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Topic#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see elixir.of.things.elixirOfThings.Topic#getName()
   * @see #getTopic()
   * @generated
   */
  EAttribute getTopic_Name();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Topic#getQos <em>Qos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Qos</em>'.
   * @see elixir.of.things.elixirOfThings.Topic#getQos()
   * @see #getTopic()
   * @generated
   */
  EAttribute getTopic_Qos();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see elixir.of.things.elixirOfThings.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Sensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see elixir.of.things.elixirOfThings.Sensor#getName()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Name();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Sensor#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see elixir.of.things.elixirOfThings.Sensor#getType()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Type();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Sensor#getGpioPin <em>Gpio Pin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gpio Pin</em>'.
   * @see elixir.of.things.elixirOfThings.Sensor#getGpioPin()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_GpioPin();

  /**
   * Returns the meta object for the containment reference '{@link elixir.of.things.elixirOfThings.Sensor#getSampleRate <em>Sample Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sample Rate</em>'.
   * @see elixir.of.things.elixirOfThings.Sensor#getSampleRate()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_SampleRate();

  /**
   * Returns the meta object for the reference '{@link elixir.of.things.elixirOfThings.Sensor#getDeployedOn <em>Deployed On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Deployed On</em>'.
   * @see elixir.of.things.elixirOfThings.Sensor#getDeployedOn()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_DeployedOn();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.Sensor#getTriggers <em>Triggers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Triggers</em>'.
   * @see elixir.of.things.elixirOfThings.Sensor#getTriggers()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Triggers();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.Trigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger</em>'.
   * @see elixir.of.things.elixirOfThings.Trigger
   * @generated
   */
  EClass getTrigger();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Trigger#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see elixir.of.things.elixirOfThings.Trigger#getName()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Name();

  /**
   * Returns the meta object for the containment reference '{@link elixir.of.things.elixirOfThings.Trigger#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see elixir.of.things.elixirOfThings.Trigger#getCondition()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.Trigger#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see elixir.of.things.elixirOfThings.Trigger#getActions()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_Actions();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.TriggerCondition <em>Trigger Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger Condition</em>'.
   * @see elixir.of.things.elixirOfThings.TriggerCondition
   * @generated
   */
  EClass getTriggerCondition();

  /**
   * Returns the meta object for the containment reference '{@link elixir.of.things.elixirOfThings.TriggerCondition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see elixir.of.things.elixirOfThings.TriggerCondition#getLeft()
   * @see #getTriggerCondition()
   * @generated
   */
  EReference getTriggerCondition_Left();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.TriggerCondition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see elixir.of.things.elixirOfThings.TriggerCondition#getOperator()
   * @see #getTriggerCondition()
   * @generated
   */
  EAttribute getTriggerCondition_Operator();

  /**
   * Returns the meta object for the containment reference '{@link elixir.of.things.elixirOfThings.TriggerCondition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see elixir.of.things.elixirOfThings.TriggerCondition#getRight()
   * @see #getTriggerCondition()
   * @generated
   */
  EReference getTriggerCondition_Right();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.TriggerAction <em>Trigger Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger Action</em>'.
   * @see elixir.of.things.elixirOfThings.TriggerAction
   * @generated
   */
  EClass getTriggerAction();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.TriggerAction#getTopic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Topic</em>'.
   * @see elixir.of.things.elixirOfThings.TriggerAction#getTopic()
   * @see #getTriggerAction()
   * @generated
   */
  EAttribute getTriggerAction_Topic();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.TriggerAction#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see elixir.of.things.elixirOfThings.TriggerAction#getFields()
   * @see #getTriggerAction()
   * @generated
   */
  EReference getTriggerAction_Fields();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.Actuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actuator</em>'.
   * @see elixir.of.things.elixirOfThings.Actuator
   * @generated
   */
  EClass getActuator();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Actuator#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see elixir.of.things.elixirOfThings.Actuator#getName()
   * @see #getActuator()
   * @generated
   */
  EAttribute getActuator_Name();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Actuator#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see elixir.of.things.elixirOfThings.Actuator#getType()
   * @see #getActuator()
   * @generated
   */
  EAttribute getActuator_Type();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Actuator#getGpioPin <em>Gpio Pin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gpio Pin</em>'.
   * @see elixir.of.things.elixirOfThings.Actuator#getGpioPin()
   * @see #getActuator()
   * @generated
   */
  EAttribute getActuator_GpioPin();

  /**
   * Returns the meta object for the reference '{@link elixir.of.things.elixirOfThings.Actuator#getDeployedOn <em>Deployed On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Deployed On</em>'.
   * @see elixir.of.things.elixirOfThings.Actuator#getDeployedOn()
   * @see #getActuator()
   * @generated
   */
  EReference getActuator_DeployedOn();

  /**
   * Returns the meta object for the attribute list '{@link elixir.of.things.elixirOfThings.Actuator#getSubscribeTo <em>Subscribe To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Subscribe To</em>'.
   * @see elixir.of.things.elixirOfThings.Actuator#getSubscribeTo()
   * @see #getActuator()
   * @generated
   */
  EAttribute getActuator_SubscribeTo();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.Actuator#getMessages <em>Messages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Messages</em>'.
   * @see elixir.of.things.elixirOfThings.Actuator#getMessages()
   * @see #getActuator()
   * @generated
   */
  EReference getActuator_Messages();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.OnMessage <em>On Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>On Message</em>'.
   * @see elixir.of.things.elixirOfThings.OnMessage
   * @generated
   */
  EClass getOnMessage();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.OnMessage#getTopic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Topic</em>'.
   * @see elixir.of.things.elixirOfThings.OnMessage#getTopic()
   * @see #getOnMessage()
   * @generated
   */
  EAttribute getOnMessage_Topic();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.OnMessage#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>State</em>'.
   * @see elixir.of.things.elixirOfThings.OnMessage#getState()
   * @see #getOnMessage()
   * @generated
   */
  EAttribute getOnMessage_State();

  /**
   * Returns the meta object for the containment reference '{@link elixir.of.things.elixirOfThings.OnMessage#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duration</em>'.
   * @see elixir.of.things.elixirOfThings.OnMessage#getDuration()
   * @see #getOnMessage()
   * @generated
   */
  EReference getOnMessage_Duration();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.Coordinator <em>Coordinator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coordinator</em>'.
   * @see elixir.of.things.elixirOfThings.Coordinator
   * @generated
   */
  EClass getCoordinator();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Coordinator#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see elixir.of.things.elixirOfThings.Coordinator#getName()
   * @see #getCoordinator()
   * @generated
   */
  EAttribute getCoordinator_Name();

  /**
   * Returns the meta object for the reference '{@link elixir.of.things.elixirOfThings.Coordinator#getDeployedOn <em>Deployed On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Deployed On</em>'.
   * @see elixir.of.things.elixirOfThings.Coordinator#getDeployedOn()
   * @see #getCoordinator()
   * @generated
   */
  EReference getCoordinator_DeployedOn();

  /**
   * Returns the meta object for the attribute list '{@link elixir.of.things.elixirOfThings.Coordinator#getSubscribeTo <em>Subscribe To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Subscribe To</em>'.
   * @see elixir.of.things.elixirOfThings.Coordinator#getSubscribeTo()
   * @see #getCoordinator()
   * @generated
   */
  EAttribute getCoordinator_SubscribeTo();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.Coordinator#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see elixir.of.things.elixirOfThings.Coordinator#getRules()
   * @see #getCoordinator()
   * @generated
   */
  EReference getCoordinator_Rules();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see elixir.of.things.elixirOfThings.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Rule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see elixir.of.things.elixirOfThings.Rule#getName()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Name();

  /**
   * Returns the meta object for the containment reference '{@link elixir.of.things.elixirOfThings.Rule#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see elixir.of.things.elixirOfThings.Rule#getCondition()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.Rule#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see elixir.of.things.elixirOfThings.Rule#getActions()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Actions();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.RuleCondition <em>Rule Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Condition</em>'.
   * @see elixir.of.things.elixirOfThings.RuleCondition
   * @generated
   */
  EClass getRuleCondition();

  /**
   * Returns the meta object for the containment reference list '{@link elixir.of.things.elixirOfThings.RuleCondition#getTopics <em>Topics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Topics</em>'.
   * @see elixir.of.things.elixirOfThings.RuleCondition#getTopics()
   * @see #getRuleCondition()
   * @generated
   */
  EReference getRuleCondition_Topics();

  /**
   * Returns the meta object for the attribute list '{@link elixir.of.things.elixirOfThings.RuleCondition#getOperators <em>Operators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operators</em>'.
   * @see elixir.of.things.elixirOfThings.RuleCondition#getOperators()
   * @see #getRuleCondition()
   * @generated
   */
  EAttribute getRuleCondition_Operators();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.TopicPath <em>Topic Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Topic Path</em>'.
   * @see elixir.of.things.elixirOfThings.TopicPath
   * @generated
   */
  EClass getTopicPath();

  /**
   * Returns the meta object for the attribute list '{@link elixir.of.things.elixirOfThings.TopicPath#getSegments <em>Segments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Segments</em>'.
   * @see elixir.of.things.elixirOfThings.TopicPath#getSegments()
   * @see #getTopicPath()
   * @generated
   */
  EAttribute getTopicPath_Segments();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.RuleAction <em>Rule Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Action</em>'.
   * @see elixir.of.things.elixirOfThings.RuleAction
   * @generated
   */
  EClass getRuleAction();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.RuleAction#getTopic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Topic</em>'.
   * @see elixir.of.things.elixirOfThings.RuleAction#getTopic()
   * @see #getRuleAction()
   * @generated
   */
  EAttribute getRuleAction_Topic();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.RuleAction#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message</em>'.
   * @see elixir.of.things.elixirOfThings.RuleAction#getMessage()
   * @see #getRuleAction()
   * @generated
   */
  EAttribute getRuleAction_Message();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.Duration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Duration</em>'.
   * @see elixir.of.things.elixirOfThings.Duration
   * @generated
   */
  EClass getDuration();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Duration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see elixir.of.things.elixirOfThings.Duration#getValue()
   * @see #getDuration()
   * @generated
   */
  EAttribute getDuration_Value();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.Duration#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see elixir.of.things.elixirOfThings.Duration#getUnit()
   * @see #getDuration()
   * @generated
   */
  EAttribute getDuration_Unit();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see elixir.of.things.elixirOfThings.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.ValueExpr <em>Value Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value Expr</em>'.
   * @see elixir.of.things.elixirOfThings.ValueExpr
   * @generated
   */
  EClass getValueExpr();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.TimestampExpr <em>Timestamp Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Timestamp Expr</em>'.
   * @see elixir.of.things.elixirOfThings.TimestampExpr
   * @generated
   */
  EClass getTimestampExpr();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.LiteralInt <em>Literal Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal Int</em>'.
   * @see elixir.of.things.elixirOfThings.LiteralInt
   * @generated
   */
  EClass getLiteralInt();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.LiteralInt#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see elixir.of.things.elixirOfThings.LiteralInt#getValue()
   * @see #getLiteralInt()
   * @generated
   */
  EAttribute getLiteralInt_Value();

  /**
   * Returns the meta object for class '{@link elixir.of.things.elixirOfThings.LiteralString <em>Literal String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal String</em>'.
   * @see elixir.of.things.elixirOfThings.LiteralString
   * @generated
   */
  EClass getLiteralString();

  /**
   * Returns the meta object for the attribute '{@link elixir.of.things.elixirOfThings.LiteralString#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see elixir.of.things.elixirOfThings.LiteralString#getValue()
   * @see #getLiteralString()
   * @generated
   */
  EAttribute getLiteralString_Value();

  /**
   * Returns the meta object for enum '{@link elixir.of.things.elixirOfThings.SensorType <em>Sensor Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Sensor Type</em>'.
   * @see elixir.of.things.elixirOfThings.SensorType
   * @generated
   */
  EEnum getSensorType();

  /**
   * Returns the meta object for enum '{@link elixir.of.things.elixirOfThings.ActuatorType <em>Actuator Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Actuator Type</em>'.
   * @see elixir.of.things.elixirOfThings.ActuatorType
   * @generated
   */
  EEnum getActuatorType();

  /**
   * Returns the meta object for enum '{@link elixir.of.things.elixirOfThings.QoS <em>Qo S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Qo S</em>'.
   * @see elixir.of.things.elixirOfThings.QoS
   * @generated
   */
  EEnum getQoS();

  /**
   * Returns the meta object for enum '{@link elixir.of.things.elixirOfThings.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operator</em>'.
   * @see elixir.of.things.elixirOfThings.Operator
   * @generated
   */
  EEnum getOperator();

  /**
   * Returns the meta object for enum '{@link elixir.of.things.elixirOfThings.LogicalOp <em>Logical Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Logical Op</em>'.
   * @see elixir.of.things.elixirOfThings.LogicalOp
   * @generated
   */
  EEnum getLogicalOp();

  /**
   * Returns the meta object for enum '{@link elixir.of.things.elixirOfThings.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>State</em>'.
   * @see elixir.of.things.elixirOfThings.State
   * @generated
   */
  EEnum getState();

  /**
   * Returns the meta object for enum '{@link elixir.of.things.elixirOfThings.TimeUnit <em>Time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Time Unit</em>'.
   * @see elixir.of.things.elixirOfThings.TimeUnit
   * @generated
   */
  EEnum getTimeUnit();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ElixirOfThingsFactory getElixirOfThingsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.SystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.SystemImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getSystem()
     * @generated
     */
    EClass SYSTEM = eINSTANCE.getSystem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM__NAME = eINSTANCE.getSystem_Name();

    /**
     * The meta object literal for the '<em><b>Broker</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__BROKER = eINSTANCE.getSystem_Broker();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__NODES = eINSTANCE.getSystem_Nodes();

    /**
     * The meta object literal for the '<em><b>Topics</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__TOPICS = eINSTANCE.getSystem_Topics();

    /**
     * The meta object literal for the '<em><b>Sensors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__SENSORS = eINSTANCE.getSystem_Sensors();

    /**
     * The meta object literal for the '<em><b>Actuators</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__ACTUATORS = eINSTANCE.getSystem_Actuators();

    /**
     * The meta object literal for the '<em><b>Coordinators</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__COORDINATORS = eINSTANCE.getSystem_Coordinators();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.BrokerImpl <em>Broker</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.BrokerImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getBroker()
     * @generated
     */
    EClass BROKER = eINSTANCE.getBroker();

    /**
     * The meta object literal for the '<em><b>Host</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BROKER__HOST = eINSTANCE.getBroker_Host();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BROKER__PORT = eINSTANCE.getBroker_Port();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.NodeImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NAME = eINSTANCE.getNode_Name();

    /**
     * The meta object literal for the '<em><b>Ip Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__IP_ADDRESS = eINSTANCE.getNode_IpAddress();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.TopicImpl <em>Topic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.TopicImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTopic()
     * @generated
     */
    EClass TOPIC = eINSTANCE.getTopic();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOPIC__NAME = eINSTANCE.getTopic_Name();

    /**
     * The meta object literal for the '<em><b>Qos</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOPIC__QOS = eINSTANCE.getTopic_Qos();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.SensorImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__NAME = eINSTANCE.getSensor_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__TYPE = eINSTANCE.getSensor_Type();

    /**
     * The meta object literal for the '<em><b>Gpio Pin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__GPIO_PIN = eINSTANCE.getSensor_GpioPin();

    /**
     * The meta object literal for the '<em><b>Sample Rate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__SAMPLE_RATE = eINSTANCE.getSensor_SampleRate();

    /**
     * The meta object literal for the '<em><b>Deployed On</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__DEPLOYED_ON = eINSTANCE.getSensor_DeployedOn();

    /**
     * The meta object literal for the '<em><b>Triggers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__TRIGGERS = eINSTANCE.getSensor_Triggers();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.TriggerImpl <em>Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.TriggerImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTrigger()
     * @generated
     */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__NAME = eINSTANCE.getTrigger_Name();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__CONDITION = eINSTANCE.getTrigger_Condition();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__ACTIONS = eINSTANCE.getTrigger_Actions();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.TriggerConditionImpl <em>Trigger Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.TriggerConditionImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTriggerCondition()
     * @generated
     */
    EClass TRIGGER_CONDITION = eINSTANCE.getTriggerCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER_CONDITION__LEFT = eINSTANCE.getTriggerCondition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER_CONDITION__OPERATOR = eINSTANCE.getTriggerCondition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER_CONDITION__RIGHT = eINSTANCE.getTriggerCondition_Right();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.TriggerActionImpl <em>Trigger Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.TriggerActionImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTriggerAction()
     * @generated
     */
    EClass TRIGGER_ACTION = eINSTANCE.getTriggerAction();

    /**
     * The meta object literal for the '<em><b>Topic</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER_ACTION__TOPIC = eINSTANCE.getTriggerAction_Topic();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER_ACTION__FIELDS = eINSTANCE.getTriggerAction_Fields();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.ActuatorImpl <em>Actuator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.ActuatorImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getActuator()
     * @generated
     */
    EClass ACTUATOR = eINSTANCE.getActuator();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTUATOR__NAME = eINSTANCE.getActuator_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTUATOR__TYPE = eINSTANCE.getActuator_Type();

    /**
     * The meta object literal for the '<em><b>Gpio Pin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTUATOR__GPIO_PIN = eINSTANCE.getActuator_GpioPin();

    /**
     * The meta object literal for the '<em><b>Deployed On</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTUATOR__DEPLOYED_ON = eINSTANCE.getActuator_DeployedOn();

    /**
     * The meta object literal for the '<em><b>Subscribe To</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTUATOR__SUBSCRIBE_TO = eINSTANCE.getActuator_SubscribeTo();

    /**
     * The meta object literal for the '<em><b>Messages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTUATOR__MESSAGES = eINSTANCE.getActuator_Messages();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.OnMessageImpl <em>On Message</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.OnMessageImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getOnMessage()
     * @generated
     */
    EClass ON_MESSAGE = eINSTANCE.getOnMessage();

    /**
     * The meta object literal for the '<em><b>Topic</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ON_MESSAGE__TOPIC = eINSTANCE.getOnMessage_Topic();

    /**
     * The meta object literal for the '<em><b>State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ON_MESSAGE__STATE = eINSTANCE.getOnMessage_State();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ON_MESSAGE__DURATION = eINSTANCE.getOnMessage_Duration();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.CoordinatorImpl <em>Coordinator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.CoordinatorImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getCoordinator()
     * @generated
     */
    EClass COORDINATOR = eINSTANCE.getCoordinator();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATOR__NAME = eINSTANCE.getCoordinator_Name();

    /**
     * The meta object literal for the '<em><b>Deployed On</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COORDINATOR__DEPLOYED_ON = eINSTANCE.getCoordinator_DeployedOn();

    /**
     * The meta object literal for the '<em><b>Subscribe To</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATOR__SUBSCRIBE_TO = eINSTANCE.getCoordinator_SubscribeTo();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COORDINATOR__RULES = eINSTANCE.getCoordinator_Rules();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.RuleImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRule_Name();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CONDITION = eINSTANCE.getRule_Condition();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__ACTIONS = eINSTANCE.getRule_Actions();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.RuleConditionImpl <em>Rule Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.RuleConditionImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getRuleCondition()
     * @generated
     */
    EClass RULE_CONDITION = eINSTANCE.getRuleCondition();

    /**
     * The meta object literal for the '<em><b>Topics</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_CONDITION__TOPICS = eINSTANCE.getRuleCondition_Topics();

    /**
     * The meta object literal for the '<em><b>Operators</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE_CONDITION__OPERATORS = eINSTANCE.getRuleCondition_Operators();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.TopicPathImpl <em>Topic Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.TopicPathImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTopicPath()
     * @generated
     */
    EClass TOPIC_PATH = eINSTANCE.getTopicPath();

    /**
     * The meta object literal for the '<em><b>Segments</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOPIC_PATH__SEGMENTS = eINSTANCE.getTopicPath_Segments();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.RuleActionImpl <em>Rule Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.RuleActionImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getRuleAction()
     * @generated
     */
    EClass RULE_ACTION = eINSTANCE.getRuleAction();

    /**
     * The meta object literal for the '<em><b>Topic</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE_ACTION__TOPIC = eINSTANCE.getRuleAction_Topic();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE_ACTION__MESSAGE = eINSTANCE.getRuleAction_Message();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.DurationImpl <em>Duration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.DurationImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getDuration()
     * @generated
     */
    EClass DURATION = eINSTANCE.getDuration();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DURATION__VALUE = eINSTANCE.getDuration_Value();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DURATION__UNIT = eINSTANCE.getDuration_Unit();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.ExpressionImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.ValueExprImpl <em>Value Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.ValueExprImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getValueExpr()
     * @generated
     */
    EClass VALUE_EXPR = eINSTANCE.getValueExpr();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.TimestampExprImpl <em>Timestamp Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.TimestampExprImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTimestampExpr()
     * @generated
     */
    EClass TIMESTAMP_EXPR = eINSTANCE.getTimestampExpr();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.LiteralIntImpl <em>Literal Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.LiteralIntImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getLiteralInt()
     * @generated
     */
    EClass LITERAL_INT = eINSTANCE.getLiteralInt();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAL_INT__VALUE = eINSTANCE.getLiteralInt_Value();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.impl.LiteralStringImpl <em>Literal String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.impl.LiteralStringImpl
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getLiteralString()
     * @generated
     */
    EClass LITERAL_STRING = eINSTANCE.getLiteralString();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAL_STRING__VALUE = eINSTANCE.getLiteralString_Value();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.SensorType <em>Sensor Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.SensorType
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getSensorType()
     * @generated
     */
    EEnum SENSOR_TYPE = eINSTANCE.getSensorType();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.ActuatorType <em>Actuator Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.ActuatorType
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getActuatorType()
     * @generated
     */
    EEnum ACTUATOR_TYPE = eINSTANCE.getActuatorType();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.QoS <em>Qo S</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.QoS
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getQoS()
     * @generated
     */
    EEnum QO_S = eINSTANCE.getQoS();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.Operator <em>Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.Operator
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getOperator()
     * @generated
     */
    EEnum OPERATOR = eINSTANCE.getOperator();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.LogicalOp <em>Logical Op</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.LogicalOp
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getLogicalOp()
     * @generated
     */
    EEnum LOGICAL_OP = eINSTANCE.getLogicalOp();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.State <em>State</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.State
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getState()
     * @generated
     */
    EEnum STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '{@link elixir.of.things.elixirOfThings.TimeUnit <em>Time Unit</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see elixir.of.things.elixirOfThings.TimeUnit
     * @see elixir.of.things.elixirOfThings.impl.ElixirOfThingsPackageImpl#getTimeUnit()
     * @generated
     */
    EEnum TIME_UNIT = eINSTANCE.getTimeUnit();

  }

} //ElixirOfThingsPackage
