/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Topic</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link elixir.of.things.elixirOfThings.Topic#getName <em>Name</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.Topic#getQos <em>Qos</em>}</li>
 * </ul>
 *
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getTopic()
 * @model
 * @generated
 */
public interface Topic extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getTopic_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.Topic#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Qos</b></em>' attribute.
   * The literals are from the enumeration {@link elixir.of.things.elixirOfThings.QoS}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qos</em>' attribute.
   * @see elixir.of.things.elixirOfThings.QoS
   * @see #setQos(QoS)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getTopic_Qos()
   * @model
   * @generated
   */
  QoS getQos();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.Topic#getQos <em>Qos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qos</em>' attribute.
   * @see elixir.of.things.elixirOfThings.QoS
   * @see #getQos()
   * @generated
   */
  void setQos(QoS value);

} // Topic
