/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trigger Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link elixir.of.things.elixirOfThings.TriggerCondition#getLeft <em>Left</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.TriggerCondition#getOperator <em>Operator</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.TriggerCondition#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getTriggerCondition()
 * @model
 * @generated
 */
public interface TriggerCondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Expression)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getTriggerCondition_Left()
   * @model containment="true"
   * @generated
   */
  Expression getLeft();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.TriggerCondition#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Expression value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link elixir.of.things.elixirOfThings.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see elixir.of.things.elixirOfThings.Operator
   * @see #setOperator(Operator)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getTriggerCondition_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.TriggerCondition#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see elixir.of.things.elixirOfThings.Operator
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Expression)
   * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getTriggerCondition_Right()
   * @model containment="true"
   * @generated
   */
  Expression getRight();

  /**
   * Sets the value of the '{@link elixir.of.things.elixirOfThings.TriggerCondition#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Expression value);

} // TriggerCondition
