/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see elixir.of.things.elixirOfThings.ElixirOfThingsPackage#getValueExpr()
 * @model
 * @generated
 */
public interface ValueExpr extends Expression
{
} // ValueExpr
