/*
 * generated by Xtext 2.41.0
 */
package elixir.of.things.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import elixir.of.things.ElixirOfThingsRuntimeModule;
import elixir.of.things.ElixirOfThingsStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ElixirOfThingsIdeSetup extends ElixirOfThingsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ElixirOfThingsRuntimeModule(), new ElixirOfThingsIdeModule()));
	}
	
}
