/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings.impl;

import elixir.of.things.elixirOfThings.Actuator;
import elixir.of.things.elixirOfThings.ActuatorType;
import elixir.of.things.elixirOfThings.BoolAndExpr;
import elixir.of.things.elixirOfThings.BoolExpr;
import elixir.of.things.elixirOfThings.BoolNotExpr;
import elixir.of.things.elixirOfThings.BoolOrExpr;
import elixir.of.things.elixirOfThings.Broker;
import elixir.of.things.elixirOfThings.Coordinator;
import elixir.of.things.elixirOfThings.ElixirOfThingsFactory;
import elixir.of.things.elixirOfThings.ElixirOfThingsPackage;
import elixir.of.things.elixirOfThings.Node;
import elixir.of.things.elixirOfThings.NumAddExpr;
import elixir.of.things.elixirOfThings.NumDivExpr;
import elixir.of.things.elixirOfThings.NumExpr;
import elixir.of.things.elixirOfThings.NumLiteral;
import elixir.of.things.elixirOfThings.NumMulExpr;
import elixir.of.things.elixirOfThings.NumSubExpr;
import elixir.of.things.elixirOfThings.OnMessage;
import elixir.of.things.elixirOfThings.Operator;
import elixir.of.things.elixirOfThings.PublishField;
import elixir.of.things.elixirOfThings.QoS;
import elixir.of.things.elixirOfThings.Rule;
import elixir.of.things.elixirOfThings.RuleAction;
import elixir.of.things.elixirOfThings.RuleCondition;
import elixir.of.things.elixirOfThings.SampleRate;
import elixir.of.things.elixirOfThings.Sensor;
import elixir.of.things.elixirOfThings.SensorType;
import elixir.of.things.elixirOfThings.State;
import elixir.of.things.elixirOfThings.TimeUnit;
import elixir.of.things.elixirOfThings.TimestampField;
import elixir.of.things.elixirOfThings.Topic;
import elixir.of.things.elixirOfThings.TopicRef;
import elixir.of.things.elixirOfThings.Trigger;
import elixir.of.things.elixirOfThings.TriggerAction;
import elixir.of.things.elixirOfThings.TriggerCondition;
import elixir.of.things.elixirOfThings.ValueField;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ElixirOfThingsFactoryImpl extends EFactoryImpl implements ElixirOfThingsFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ElixirOfThingsFactory init()
  {
    try
    {
      ElixirOfThingsFactory theElixirOfThingsFactory = (ElixirOfThingsFactory)EPackage.Registry.INSTANCE.getEFactory(ElixirOfThingsPackage.eNS_URI);
      if (theElixirOfThingsFactory != null)
      {
        return theElixirOfThingsFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ElixirOfThingsFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ElixirOfThingsFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ElixirOfThingsPackage.SYSTEM: return createSystem();
      case ElixirOfThingsPackage.BROKER: return createBroker();
      case ElixirOfThingsPackage.NODE: return createNode();
      case ElixirOfThingsPackage.TOPIC: return createTopic();
      case ElixirOfThingsPackage.SENSOR: return createSensor();
      case ElixirOfThingsPackage.SAMPLE_RATE: return createSampleRate();
      case ElixirOfThingsPackage.NUM_EXPR: return createNumExpr();
      case ElixirOfThingsPackage.TRIGGER: return createTrigger();
      case ElixirOfThingsPackage.TRIGGER_CONDITION: return createTriggerCondition();
      case ElixirOfThingsPackage.TRIGGER_ACTION: return createTriggerAction();
      case ElixirOfThingsPackage.PUBLISH_FIELD: return createPublishField();
      case ElixirOfThingsPackage.ACTUATOR: return createActuator();
      case ElixirOfThingsPackage.ON_MESSAGE: return createOnMessage();
      case ElixirOfThingsPackage.COORDINATOR: return createCoordinator();
      case ElixirOfThingsPackage.RULE: return createRule();
      case ElixirOfThingsPackage.RULE_CONDITION: return createRuleCondition();
      case ElixirOfThingsPackage.BOOL_EXPR: return createBoolExpr();
      case ElixirOfThingsPackage.RULE_ACTION: return createRuleAction();
      case ElixirOfThingsPackage.NUM_ADD_EXPR: return createNumAddExpr();
      case ElixirOfThingsPackage.NUM_SUB_EXPR: return createNumSubExpr();
      case ElixirOfThingsPackage.NUM_MUL_EXPR: return createNumMulExpr();
      case ElixirOfThingsPackage.NUM_DIV_EXPR: return createNumDivExpr();
      case ElixirOfThingsPackage.NUM_LITERAL: return createNumLiteral();
      case ElixirOfThingsPackage.VALUE_FIELD: return createValueField();
      case ElixirOfThingsPackage.TIMESTAMP_FIELD: return createTimestampField();
      case ElixirOfThingsPackage.BOOL_OR_EXPR: return createBoolOrExpr();
      case ElixirOfThingsPackage.BOOL_AND_EXPR: return createBoolAndExpr();
      case ElixirOfThingsPackage.BOOL_NOT_EXPR: return createBoolNotExpr();
      case ElixirOfThingsPackage.TOPIC_REF: return createTopicRef();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case ElixirOfThingsPackage.SENSOR_TYPE:
        return createSensorTypeFromString(eDataType, initialValue);
      case ElixirOfThingsPackage.ACTUATOR_TYPE:
        return createActuatorTypeFromString(eDataType, initialValue);
      case ElixirOfThingsPackage.QO_S:
        return createQoSFromString(eDataType, initialValue);
      case ElixirOfThingsPackage.OPERATOR:
        return createOperatorFromString(eDataType, initialValue);
      case ElixirOfThingsPackage.STATE:
        return createStateFromString(eDataType, initialValue);
      case ElixirOfThingsPackage.TIME_UNIT:
        return createTimeUnitFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case ElixirOfThingsPackage.SENSOR_TYPE:
        return convertSensorTypeToString(eDataType, instanceValue);
      case ElixirOfThingsPackage.ACTUATOR_TYPE:
        return convertActuatorTypeToString(eDataType, instanceValue);
      case ElixirOfThingsPackage.QO_S:
        return convertQoSToString(eDataType, instanceValue);
      case ElixirOfThingsPackage.OPERATOR:
        return convertOperatorToString(eDataType, instanceValue);
      case ElixirOfThingsPackage.STATE:
        return convertStateToString(eDataType, instanceValue);
      case ElixirOfThingsPackage.TIME_UNIT:
        return convertTimeUnitToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public elixir.of.things.elixirOfThings.System createSystem()
  {
    SystemImpl system = new SystemImpl();
    return system;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Broker createBroker()
  {
    BrokerImpl broker = new BrokerImpl();
    return broker;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Node createNode()
  {
    NodeImpl node = new NodeImpl();
    return node;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Topic createTopic()
  {
    TopicImpl topic = new TopicImpl();
    return topic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sensor createSensor()
  {
    SensorImpl sensor = new SensorImpl();
    return sensor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SampleRate createSampleRate()
  {
    SampleRateImpl sampleRate = new SampleRateImpl();
    return sampleRate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NumExpr createNumExpr()
  {
    NumExprImpl numExpr = new NumExprImpl();
    return numExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Trigger createTrigger()
  {
    TriggerImpl trigger = new TriggerImpl();
    return trigger;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TriggerCondition createTriggerCondition()
  {
    TriggerConditionImpl triggerCondition = new TriggerConditionImpl();
    return triggerCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TriggerAction createTriggerAction()
  {
    TriggerActionImpl triggerAction = new TriggerActionImpl();
    return triggerAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PublishField createPublishField()
  {
    PublishFieldImpl publishField = new PublishFieldImpl();
    return publishField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Actuator createActuator()
  {
    ActuatorImpl actuator = new ActuatorImpl();
    return actuator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OnMessage createOnMessage()
  {
    OnMessageImpl onMessage = new OnMessageImpl();
    return onMessage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Coordinator createCoordinator()
  {
    CoordinatorImpl coordinator = new CoordinatorImpl();
    return coordinator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rule createRule()
  {
    RuleImpl rule = new RuleImpl();
    return rule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RuleCondition createRuleCondition()
  {
    RuleConditionImpl ruleCondition = new RuleConditionImpl();
    return ruleCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BoolExpr createBoolExpr()
  {
    BoolExprImpl boolExpr = new BoolExprImpl();
    return boolExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RuleAction createRuleAction()
  {
    RuleActionImpl ruleAction = new RuleActionImpl();
    return ruleAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NumAddExpr createNumAddExpr()
  {
    NumAddExprImpl numAddExpr = new NumAddExprImpl();
    return numAddExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NumSubExpr createNumSubExpr()
  {
    NumSubExprImpl numSubExpr = new NumSubExprImpl();
    return numSubExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NumMulExpr createNumMulExpr()
  {
    NumMulExprImpl numMulExpr = new NumMulExprImpl();
    return numMulExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NumDivExpr createNumDivExpr()
  {
    NumDivExprImpl numDivExpr = new NumDivExprImpl();
    return numDivExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NumLiteral createNumLiteral()
  {
    NumLiteralImpl numLiteral = new NumLiteralImpl();
    return numLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ValueField createValueField()
  {
    ValueFieldImpl valueField = new ValueFieldImpl();
    return valueField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TimestampField createTimestampField()
  {
    TimestampFieldImpl timestampField = new TimestampFieldImpl();
    return timestampField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BoolOrExpr createBoolOrExpr()
  {
    BoolOrExprImpl boolOrExpr = new BoolOrExprImpl();
    return boolOrExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BoolAndExpr createBoolAndExpr()
  {
    BoolAndExprImpl boolAndExpr = new BoolAndExprImpl();
    return boolAndExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BoolNotExpr createBoolNotExpr()
  {
    BoolNotExprImpl boolNotExpr = new BoolNotExprImpl();
    return boolNotExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TopicRef createTopicRef()
  {
    TopicRefImpl topicRef = new TopicRefImpl();
    return topicRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SensorType createSensorTypeFromString(EDataType eDataType, String initialValue)
  {
    SensorType result = SensorType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertSensorTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ActuatorType createActuatorTypeFromString(EDataType eDataType, String initialValue)
  {
    ActuatorType result = ActuatorType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertActuatorTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public QoS createQoSFromString(EDataType eDataType, String initialValue)
  {
    QoS result = QoS.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertQoSToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Operator createOperatorFromString(EDataType eDataType, String initialValue)
  {
    Operator result = Operator.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertOperatorToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public State createStateFromString(EDataType eDataType, String initialValue)
  {
    State result = State.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertStateToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TimeUnit createTimeUnitFromString(EDataType eDataType, String initialValue)
  {
    TimeUnit result = TimeUnit.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertTimeUnitToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ElixirOfThingsPackage getElixirOfThingsPackage()
  {
    return (ElixirOfThingsPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ElixirOfThingsPackage getPackage()
  {
    return ElixirOfThingsPackage.eINSTANCE;
  }

} //ElixirOfThingsFactoryImpl
