/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings.impl;

import elixir.of.things.elixirOfThings.ElixirOfThingsPackage;
import elixir.of.things.elixirOfThings.Expression;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpressionImpl extends MinimalEObjectImpl.Container implements Expression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ElixirOfThingsPackage.Literals.EXPRESSION;
  }

} //ExpressionImpl
