/**
 * generated by Xtext 2.41.0
 */
package elixir.of.things.elixirOfThings.impl;

import elixir.of.things.elixirOfThings.ElixirOfThingsPackage;
import elixir.of.things.elixirOfThings.PublishField;
import elixir.of.things.elixirOfThings.Topic;
import elixir.of.things.elixirOfThings.TriggerAction;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Trigger Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link elixir.of.things.elixirOfThings.impl.TriggerActionImpl#getTopic <em>Topic</em>}</li>
 *   <li>{@link elixir.of.things.elixirOfThings.impl.TriggerActionImpl#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TriggerActionImpl extends MinimalEObjectImpl.Container implements TriggerAction
{
  /**
   * The cached value of the '{@link #getTopic() <em>Topic</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTopic()
   * @generated
   * @ordered
   */
  protected Topic topic;

  /**
   * The cached value of the '{@link #getFields() <em>Fields</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFields()
   * @generated
   * @ordered
   */
  protected EList<PublishField> fields;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TriggerActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ElixirOfThingsPackage.Literals.TRIGGER_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Topic getTopic()
  {
    if (topic != null && topic.eIsProxy())
    {
      InternalEObject oldTopic = (InternalEObject)topic;
      topic = (Topic)eResolveProxy(oldTopic);
      if (topic != oldTopic)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ElixirOfThingsPackage.TRIGGER_ACTION__TOPIC, oldTopic, topic));
      }
    }
    return topic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Topic basicGetTopic()
  {
    return topic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTopic(Topic newTopic)
  {
    Topic oldTopic = topic;
    topic = newTopic;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ElixirOfThingsPackage.TRIGGER_ACTION__TOPIC, oldTopic, topic));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PublishField> getFields()
  {
    if (fields == null)
    {
      fields = new EObjectContainmentEList<PublishField>(PublishField.class, this, ElixirOfThingsPackage.TRIGGER_ACTION__FIELDS);
    }
    return fields;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ElixirOfThingsPackage.TRIGGER_ACTION__FIELDS:
        return ((InternalEList<?>)getFields()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ElixirOfThingsPackage.TRIGGER_ACTION__TOPIC:
        if (resolve) return getTopic();
        return basicGetTopic();
      case ElixirOfThingsPackage.TRIGGER_ACTION__FIELDS:
        return getFields();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ElixirOfThingsPackage.TRIGGER_ACTION__TOPIC:
        setTopic((Topic)newValue);
        return;
      case ElixirOfThingsPackage.TRIGGER_ACTION__FIELDS:
        getFields().clear();
        getFields().addAll((Collection<? extends PublishField>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ElixirOfThingsPackage.TRIGGER_ACTION__TOPIC:
        setTopic((Topic)null);
        return;
      case ElixirOfThingsPackage.TRIGGER_ACTION__FIELDS:
        getFields().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ElixirOfThingsPackage.TRIGGER_ACTION__TOPIC:
        return topic != null;
      case ElixirOfThingsPackage.TRIGGER_ACTION__FIELDS:
        return fields != null && !fields.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //TriggerActionImpl
