/*
 * generated by Xtext 2.41.0
 */
package elixir.of.things.parser.antlr;

import com.google.inject.Inject;
import elixir.of.things.parser.antlr.internal.InternalElixirOfThingsParser;
import elixir.of.things.services.ElixirOfThingsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ElixirOfThingsParser extends AbstractAntlrParser {

	@Inject
	private ElixirOfThingsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalElixirOfThingsParser createParser(XtextTokenStream stream) {
		return new InternalElixirOfThingsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "System";
	}

	public ElixirOfThingsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ElixirOfThingsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
