/*
 * generated by Xtext 2.41.0
 */
grammar InternalElixirOfThings;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package elixir.of.things.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package elixir.of.things.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import elixir.of.things.services.ElixirOfThingsGrammarAccess;

}

@parser::members {

 	private ElixirOfThingsGrammarAccess grammarAccess;

    public InternalElixirOfThingsParser(TokenStream input, ElixirOfThingsGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "System";
   	}

   	@Override
   	protected ElixirOfThingsGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleSystem
entryRuleSystem returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSystemRule()); }
	iv_ruleSystem=ruleSystem
	{ $current=$iv_ruleSystem.current; }
	EOF;

// Rule System
ruleSystem returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='system'
		{
			newLeafNode(otherlv_0, grammarAccess.getSystemAccess().getSystemKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getSystemAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSystemRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getSystemAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSystemAccess().getBrokerBrokerParserRuleCall_3_0());
				}
				lv_broker_3_0=ruleBroker
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSystemRule());
					}
					set(
						$current,
						"broker",
						lv_broker_3_0,
						"elixir.of.things.ElixirOfThings.Broker");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getSystemAccess().getNodesNodeParserRuleCall_4_0());
				}
				lv_nodes_4_0=ruleNode
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSystemRule());
					}
					add(
						$current,
						"nodes",
						lv_nodes_4_0,
						"elixir.of.things.ElixirOfThings.Node");
					afterParserOrEnumRuleCall();
				}
			)
		)+
		(
			(
				{
					newCompositeNode(grammarAccess.getSystemAccess().getTopicsTopicParserRuleCall_5_0());
				}
				lv_topics_5_0=ruleTopic
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSystemRule());
					}
					add(
						$current,
						"topics",
						lv_topics_5_0,
						"elixir.of.things.ElixirOfThings.Topic");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getSystemAccess().getSensorsSensorParserRuleCall_6_0_0());
					}
					lv_sensors_6_0=ruleSensor
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSystemRule());
						}
						add(
							$current,
							"sensors",
							lv_sensors_6_0,
							"elixir.of.things.ElixirOfThings.Sensor");
						afterParserOrEnumRuleCall();
					}
				)
			)
			    |
			(
				(
					{
						newCompositeNode(grammarAccess.getSystemAccess().getActuatorsActuatorParserRuleCall_6_1_0());
					}
					lv_actuators_7_0=ruleActuator
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSystemRule());
						}
						add(
							$current,
							"actuators",
							lv_actuators_7_0,
							"elixir.of.things.ElixirOfThings.Actuator");
						afterParserOrEnumRuleCall();
					}
				)
			)
			    |
			(
				(
					{
						newCompositeNode(grammarAccess.getSystemAccess().getCoordinatorsCoordinatorParserRuleCall_6_2_0());
					}
					lv_coordinators_8_0=ruleCoordinator
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getSystemRule());
						}
						add(
							$current,
							"coordinators",
							lv_coordinators_8_0,
							"elixir.of.things.ElixirOfThings.Coordinator");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_9='}'
		{
			newLeafNode(otherlv_9, grammarAccess.getSystemAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRuleBroker
entryRuleBroker returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBrokerRule()); }
	iv_ruleBroker=ruleBroker
	{ $current=$iv_ruleBroker.current; }
	EOF;

// Rule Broker
ruleBroker returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='broker:'
		{
			newLeafNode(otherlv_0, grammarAccess.getBrokerAccess().getBrokerKeyword_0());
		}
		(
			(
				lv_host_1_0=RULE_STRING
				{
					newLeafNode(lv_host_1_0, grammarAccess.getBrokerAccess().getHostSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBrokerRule());
					}
					setWithLastConsumed(
						$current,
						"host",
						lv_host_1_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_2='port:'
		{
			newLeafNode(otherlv_2, grammarAccess.getBrokerAccess().getPortKeyword_2());
		}
		(
			(
				lv_port_3_0=RULE_INT
				{
					newLeafNode(lv_port_3_0, grammarAccess.getBrokerAccess().getPortINTTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getBrokerRule());
					}
					setWithLastConsumed(
						$current,
						"port",
						lv_port_3_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

// Entry rule entryRuleNode
entryRuleNode returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNodeRule()); }
	iv_ruleNode=ruleNode
	{ $current=$iv_ruleNode.current; }
	EOF;

// Rule Node
ruleNode returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='node'
		{
			newLeafNode(otherlv_0, grammarAccess.getNodeAccess().getNodeKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getNodeAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getNodeRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
	)
;

// Entry rule entryRuleTopic
entryRuleTopic returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTopicRule()); }
	iv_ruleTopic=ruleTopic
	{ $current=$iv_ruleTopic.current; }
	EOF;

// Rule Topic
ruleTopic returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='topic'
		{
			newLeafNode(otherlv_0, grammarAccess.getTopicAccess().getTopicKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getTopicAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTopicRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='='
		{
			newLeafNode(otherlv_2, grammarAccess.getTopicAccess().getEqualsSignKeyword_2());
		}
		otherlv_3='('
		{
			newLeafNode(otherlv_3, grammarAccess.getTopicAccess().getLeftParenthesisKeyword_3());
		}
		(
			(
				lv_topicString_4_0=RULE_STRING
				{
					newLeafNode(lv_topicString_4_0, grammarAccess.getTopicAccess().getTopicStringSTRINGTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTopicRule());
					}
					setWithLastConsumed(
						$current,
						"topicString",
						lv_topicString_4_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_5=','
		{
			newLeafNode(otherlv_5, grammarAccess.getTopicAccess().getCommaKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTopicAccess().getQosQoSEnumRuleCall_6_0());
				}
				lv_qos_6_0=ruleQoS
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTopicRule());
					}
					set(
						$current,
						"qos",
						lv_qos_6_0,
						"elixir.of.things.ElixirOfThings.QoS");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7=')'
		{
			newLeafNode(otherlv_7, grammarAccess.getTopicAccess().getRightParenthesisKeyword_7());
		}
	)
;

// Entry rule entryRuleSensor
entryRuleSensor returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSensorRule()); }
	iv_ruleSensor=ruleSensor
	{ $current=$iv_ruleSensor.current; }
	EOF;

// Rule Sensor
ruleSensor returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='sensor'
		{
			newLeafNode(otherlv_0, grammarAccess.getSensorAccess().getSensorKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getSensorAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSensorRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getSensorAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='type:'
		{
			newLeafNode(otherlv_3, grammarAccess.getSensorAccess().getTypeKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSensorAccess().getTypeSensorTypeEnumRuleCall_4_0());
				}
				lv_type_4_0=ruleSensorType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSensorRule());
					}
					set(
						$current,
						"type",
						lv_type_4_0,
						"elixir.of.things.ElixirOfThings.SensorType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='gpioPin:'
		{
			newLeafNode(otherlv_5, grammarAccess.getSensorAccess().getGpioPinKeyword_5());
		}
		(
			(
				lv_gpioPin_6_0=RULE_INT
				{
					newLeafNode(lv_gpioPin_6_0, grammarAccess.getSensorAccess().getGpioPinINTTerminalRuleCall_6_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSensorRule());
					}
					setWithLastConsumed(
						$current,
						"gpioPin",
						lv_gpioPin_6_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_7='sampleRate:'
		{
			newLeafNode(otherlv_7, grammarAccess.getSensorAccess().getSampleRateKeyword_7());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSensorAccess().getSampleRateDurationParserRuleCall_8_0());
				}
				lv_sampleRate_8_0=ruleDuration
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSensorRule());
					}
					set(
						$current,
						"sampleRate",
						lv_sampleRate_8_0,
						"elixir.of.things.ElixirOfThings.Duration");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_9='deployedOn:'
		{
			newLeafNode(otherlv_9, grammarAccess.getSensorAccess().getDeployedOnKeyword_9());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSensorRule());
					}
				}
				otherlv_10=RULE_ID
				{
					newLeafNode(otherlv_10, grammarAccess.getSensorAccess().getDeployedOnNodeCrossReference_10_0());
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getSensorAccess().getTriggersTriggerParserRuleCall_11_0());
				}
				lv_triggers_11_0=ruleTrigger
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSensorRule());
					}
					add(
						$current,
						"triggers",
						lv_triggers_11_0,
						"elixir.of.things.ElixirOfThings.Trigger");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_12='}'
		{
			newLeafNode(otherlv_12, grammarAccess.getSensorAccess().getRightCurlyBracketKeyword_12());
		}
	)
;

// Entry rule entryRuleTrigger
entryRuleTrigger returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTriggerRule()); }
	iv_ruleTrigger=ruleTrigger
	{ $current=$iv_ruleTrigger.current; }
	EOF;

// Rule Trigger
ruleTrigger returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='trigger'
		{
			newLeafNode(otherlv_0, grammarAccess.getTriggerAccess().getTriggerKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getTriggerAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTriggerRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getTriggerAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTriggerAccess().getConditionTriggerConditionParserRuleCall_3_0());
				}
				lv_condition_3_0=ruleTriggerCondition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTriggerRule());
					}
					set(
						$current,
						"condition",
						lv_condition_3_0,
						"elixir.of.things.ElixirOfThings.TriggerCondition");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getTriggerAccess().getActionsTriggerActionParserRuleCall_4_0());
				}
				lv_actions_4_0=ruleTriggerAction
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTriggerRule());
					}
					add(
						$current,
						"actions",
						lv_actions_4_0,
						"elixir.of.things.ElixirOfThings.TriggerAction");
					afterParserOrEnumRuleCall();
				}
			)
		)+
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getTriggerAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleTriggerCondition
entryRuleTriggerCondition returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTriggerConditionRule()); }
	iv_ruleTriggerCondition=ruleTriggerCondition
	{ $current=$iv_ruleTriggerCondition.current; }
	EOF;

// Rule TriggerCondition
ruleTriggerCondition returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='when'
		{
			newLeafNode(otherlv_0, grammarAccess.getTriggerConditionAccess().getWhenKeyword_0());
		}
		otherlv_1='value'
		{
			newLeafNode(otherlv_1, grammarAccess.getTriggerConditionAccess().getValueKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTriggerConditionAccess().getOperatorOperatorEnumRuleCall_2_0());
				}
				lv_operator_2_0=ruleOperator
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTriggerConditionRule());
					}
					set(
						$current,
						"operator",
						lv_operator_2_0,
						"elixir.of.things.ElixirOfThings.Operator");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				lv_right_3_0=RULE_INT
				{
					newLeafNode(lv_right_3_0, grammarAccess.getTriggerConditionAccess().getRightINTTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTriggerConditionRule());
					}
					setWithLastConsumed(
						$current,
						"right",
						lv_right_3_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_4=':'
		{
			newLeafNode(otherlv_4, grammarAccess.getTriggerConditionAccess().getColonKeyword_4());
		}
	)
;

// Entry rule entryRuleTriggerAction
entryRuleTriggerAction returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTriggerActionRule()); }
	iv_ruleTriggerAction=ruleTriggerAction
	{ $current=$iv_ruleTriggerAction.current; }
	EOF;

// Rule TriggerAction
ruleTriggerAction returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='publish'
		{
			newLeafNode(otherlv_0, grammarAccess.getTriggerActionAccess().getPublishKeyword_0());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getTriggerActionRule());
					}
				}
				otherlv_1=RULE_ID
				{
					newLeafNode(otherlv_1, grammarAccess.getTriggerActionAccess().getTopicTopicCrossReference_1_0());
				}
			)
		)
		otherlv_2=':'
		{
			newLeafNode(otherlv_2, grammarAccess.getTriggerActionAccess().getColonKeyword_2());
		}
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getTriggerActionAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTriggerActionAccess().getFieldsPublishFieldParserRuleCall_4_0());
				}
				lv_fields_4_0=rulePublishField
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTriggerActionRule());
					}
					add(
						$current,
						"fields",
						lv_fields_4_0,
						"elixir.of.things.ElixirOfThings.PublishField");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_5=','
			{
				newLeafNode(otherlv_5, grammarAccess.getTriggerActionAccess().getCommaKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getTriggerActionAccess().getFieldsPublishFieldParserRuleCall_5_1_0());
					}
					lv_fields_6_0=rulePublishField
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getTriggerActionRule());
						}
						add(
							$current,
							"fields",
							lv_fields_6_0,
							"elixir.of.things.ElixirOfThings.PublishField");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getTriggerActionAccess().getRightCurlyBracketKeyword_6());
		}
	)
;

// Entry rule entryRulePublishField
entryRulePublishField returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPublishFieldRule()); }
	iv_rulePublishField=rulePublishField
	{ $current=$iv_rulePublishField.current; }
	EOF;

// Rule PublishField
rulePublishField returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					$current = forceCreateModelElement(
						grammarAccess.getPublishFieldAccess().getValueFieldAction_0_0(),
						$current);
				}
			)
			otherlv_1='value'
			{
				newLeafNode(otherlv_1, grammarAccess.getPublishFieldAccess().getValueKeyword_0_1());
			}
		)
		    |
		(
			(
				{
					$current = forceCreateModelElement(
						grammarAccess.getPublishFieldAccess().getTimestampFieldAction_1_0(),
						$current);
				}
			)
			otherlv_3='timestamp'
			{
				newLeafNode(otherlv_3, grammarAccess.getPublishFieldAccess().getTimestampKeyword_1_1());
			}
		)
	)
;

// Entry rule entryRuleActuator
entryRuleActuator returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getActuatorRule()); }
	iv_ruleActuator=ruleActuator
	{ $current=$iv_ruleActuator.current; }
	EOF;

// Rule Actuator
ruleActuator returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='actuator'
		{
			newLeafNode(otherlv_0, grammarAccess.getActuatorAccess().getActuatorKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getActuatorAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getActuatorRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getActuatorAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='type:'
		{
			newLeafNode(otherlv_3, grammarAccess.getActuatorAccess().getTypeKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getActuatorAccess().getTypeActuatorTypeEnumRuleCall_4_0());
				}
				lv_type_4_0=ruleActuatorType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getActuatorRule());
					}
					set(
						$current,
						"type",
						lv_type_4_0,
						"elixir.of.things.ElixirOfThings.ActuatorType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='gpioPin:'
		{
			newLeafNode(otherlv_5, grammarAccess.getActuatorAccess().getGpioPinKeyword_5());
		}
		(
			(
				lv_gpioPin_6_0=RULE_INT
				{
					newLeafNode(lv_gpioPin_6_0, grammarAccess.getActuatorAccess().getGpioPinINTTerminalRuleCall_6_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getActuatorRule());
					}
					setWithLastConsumed(
						$current,
						"gpioPin",
						lv_gpioPin_6_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_7='deployedOn:'
		{
			newLeafNode(otherlv_7, grammarAccess.getActuatorAccess().getDeployedOnKeyword_7());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getActuatorRule());
					}
				}
				otherlv_8=RULE_ID
				{
					newLeafNode(otherlv_8, grammarAccess.getActuatorAccess().getDeployedOnNodeCrossReference_8_0());
				}
			)
		)
		otherlv_9='subscribeTo:'
		{
			newLeafNode(otherlv_9, grammarAccess.getActuatorAccess().getSubscribeToKeyword_9());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getActuatorRule());
					}
				}
				otherlv_10=RULE_ID
				{
					newLeafNode(otherlv_10, grammarAccess.getActuatorAccess().getSubscribeToTopicCrossReference_10_0());
				}
			)
		)
		(
			otherlv_11=','
			{
				newLeafNode(otherlv_11, grammarAccess.getActuatorAccess().getCommaKeyword_11_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getActuatorRule());
						}
					}
					otherlv_12=RULE_ID
					{
						newLeafNode(otherlv_12, grammarAccess.getActuatorAccess().getSubscribeToTopicCrossReference_11_1_0());
					}
				)
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getActuatorAccess().getMessagesOnMessageParserRuleCall_12_0());
				}
				lv_messages_13_0=ruleOnMessage
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getActuatorRule());
					}
					add(
						$current,
						"messages",
						lv_messages_13_0,
						"elixir.of.things.ElixirOfThings.OnMessage");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_14='}'
		{
			newLeafNode(otherlv_14, grammarAccess.getActuatorAccess().getRightCurlyBracketKeyword_13());
		}
	)
;

// Entry rule entryRuleOnMessage
entryRuleOnMessage returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getOnMessageRule()); }
	iv_ruleOnMessage=ruleOnMessage
	{ $current=$iv_ruleOnMessage.current; }
	EOF;

// Rule OnMessage
ruleOnMessage returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='on'
		{
			newLeafNode(otherlv_0, grammarAccess.getOnMessageAccess().getOnKeyword_0());
		}
		otherlv_1='message'
		{
			newLeafNode(otherlv_1, grammarAccess.getOnMessageAccess().getMessageKeyword_1());
		}
		otherlv_2='from'
		{
			newLeafNode(otherlv_2, grammarAccess.getOnMessageAccess().getFromKeyword_2());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getOnMessageRule());
					}
				}
				otherlv_3=RULE_ID
				{
					newLeafNode(otherlv_3, grammarAccess.getOnMessageAccess().getTopicTopicCrossReference_3_0());
				}
			)
		)
		otherlv_4=':'
		{
			newLeafNode(otherlv_4, grammarAccess.getOnMessageAccess().getColonKeyword_4());
		}
		otherlv_5='turn'
		{
			newLeafNode(otherlv_5, grammarAccess.getOnMessageAccess().getTurnKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getOnMessageAccess().getStateStateEnumRuleCall_6_0());
				}
				lv_state_6_0=ruleState
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getOnMessageRule());
					}
					set(
						$current,
						"state",
						lv_state_6_0,
						"elixir.of.things.ElixirOfThings.State");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_7='for'
			{
				newLeafNode(otherlv_7, grammarAccess.getOnMessageAccess().getForKeyword_7_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getOnMessageAccess().getDurationDurationParserRuleCall_7_1_0());
					}
					lv_duration_8_0=ruleDuration
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getOnMessageRule());
						}
						set(
							$current,
							"duration",
							lv_duration_8_0,
							"elixir.of.things.ElixirOfThings.Duration");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
	)
;

// Entry rule entryRuleCoordinator
entryRuleCoordinator returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCoordinatorRule()); }
	iv_ruleCoordinator=ruleCoordinator
	{ $current=$iv_ruleCoordinator.current; }
	EOF;

// Rule Coordinator
ruleCoordinator returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='coordinator'
		{
			newLeafNode(otherlv_0, grammarAccess.getCoordinatorAccess().getCoordinatorKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getCoordinatorAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getCoordinatorRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getCoordinatorAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='deployedOn:'
		{
			newLeafNode(otherlv_3, grammarAccess.getCoordinatorAccess().getDeployedOnKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getCoordinatorRule());
					}
				}
				otherlv_4=RULE_ID
				{
					newLeafNode(otherlv_4, grammarAccess.getCoordinatorAccess().getDeployedOnNodeCrossReference_4_0());
				}
			)
		)
		otherlv_5='subscribeTo:'
		{
			newLeafNode(otherlv_5, grammarAccess.getCoordinatorAccess().getSubscribeToKeyword_5());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getCoordinatorRule());
					}
				}
				otherlv_6=RULE_ID
				{
					newLeafNode(otherlv_6, grammarAccess.getCoordinatorAccess().getSubscribeToTopicCrossReference_6_0());
				}
			)
		)
		(
			otherlv_7=','
			{
				newLeafNode(otherlv_7, grammarAccess.getCoordinatorAccess().getCommaKeyword_7_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getCoordinatorRule());
						}
					}
					otherlv_8=RULE_ID
					{
						newLeafNode(otherlv_8, grammarAccess.getCoordinatorAccess().getSubscribeToTopicCrossReference_7_1_0());
					}
				)
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getCoordinatorAccess().getRulesRuleParserRuleCall_8_0());
				}
				lv_rules_9_0=ruleRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getCoordinatorRule());
					}
					add(
						$current,
						"rules",
						lv_rules_9_0,
						"elixir.of.things.ElixirOfThings.Rule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_10='}'
		{
			newLeafNode(otherlv_10, grammarAccess.getCoordinatorAccess().getRightCurlyBracketKeyword_9());
		}
	)
;

// Entry rule entryRuleRule
entryRuleRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRuleRule()); }
	iv_ruleRule=ruleRule
	{ $current=$iv_ruleRule.current; }
	EOF;

// Rule Rule
ruleRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='rule'
		{
			newLeafNode(otherlv_0, grammarAccess.getRuleAccess().getRuleKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getRuleAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRuleRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getRuleAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getRuleAccess().getConditionRuleConditionParserRuleCall_3_0());
				}
				lv_condition_3_0=ruleRuleCondition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRuleRule());
					}
					set(
						$current,
						"condition",
						lv_condition_3_0,
						"elixir.of.things.ElixirOfThings.RuleCondition");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getRuleAccess().getActionsRuleActionParserRuleCall_4_0());
				}
				lv_actions_4_0=ruleRuleAction
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRuleRule());
					}
					add(
						$current,
						"actions",
						lv_actions_4_0,
						"elixir.of.things.ElixirOfThings.RuleAction");
					afterParserOrEnumRuleCall();
				}
			)
		)+
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getRuleAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleRuleCondition
entryRuleRuleCondition returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRuleConditionRule()); }
	iv_ruleRuleCondition=ruleRuleCondition
	{ $current=$iv_ruleRuleCondition.current; }
	EOF;

// Rule RuleCondition
ruleRuleCondition returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='when'
		{
			newLeafNode(otherlv_0, grammarAccess.getRuleConditionAccess().getWhenKeyword_0());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRuleConditionRule());
					}
				}
				otherlv_1=RULE_ID
				{
					newLeafNode(otherlv_1, grammarAccess.getRuleConditionAccess().getTopicsTopicCrossReference_1_0());
				}
			)
		)
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getRuleConditionAccess().getOperatorsLogicalOpEnumRuleCall_2_0_0());
					}
					lv_operators_2_0=ruleLogicalOp
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getRuleConditionRule());
						}
						add(
							$current,
							"operators",
							lv_operators_2_0,
							"elixir.of.things.ElixirOfThings.LogicalOp");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getRuleConditionRule());
						}
					}
					otherlv_3=RULE_ID
					{
						newLeafNode(otherlv_3, grammarAccess.getRuleConditionAccess().getTopicsTopicCrossReference_2_1_0());
					}
				)
			)
		)*
		otherlv_4=':'
		{
			newLeafNode(otherlv_4, grammarAccess.getRuleConditionAccess().getColonKeyword_3());
		}
	)
;

// Entry rule entryRuleRuleAction
entryRuleRuleAction returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRuleActionRule()); }
	iv_ruleRuleAction=ruleRuleAction
	{ $current=$iv_ruleRuleAction.current; }
	EOF;

// Rule RuleAction
ruleRuleAction returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='publish'
		{
			newLeafNode(otherlv_0, grammarAccess.getRuleActionAccess().getPublishKeyword_0());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRuleActionRule());
					}
				}
				otherlv_1=RULE_ID
				{
					newLeafNode(otherlv_1, grammarAccess.getRuleActionAccess().getTopicTopicCrossReference_1_0());
				}
			)
		)
		otherlv_2=':'
		{
			newLeafNode(otherlv_2, grammarAccess.getRuleActionAccess().getColonKeyword_2());
		}
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getRuleActionAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			otherlv_4='message:'
			{
				newLeafNode(otherlv_4, grammarAccess.getRuleActionAccess().getMessageKeyword_4_0());
			}
			(
				(
					lv_message_5_0=RULE_STRING
					{
						newLeafNode(lv_message_5_0, grammarAccess.getRuleActionAccess().getMessageSTRINGTerminalRuleCall_4_1_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getRuleActionRule());
						}
						setWithLastConsumed(
							$current,
							"message",
							lv_message_5_0,
							"org.eclipse.xtext.common.Terminals.STRING");
					}
				)
			)
		)?
		otherlv_6='}'
		{
			newLeafNode(otherlv_6, grammarAccess.getRuleActionAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleDuration
entryRuleDuration returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDurationRule()); }
	iv_ruleDuration=ruleDuration
	{ $current=$iv_ruleDuration.current; }
	EOF;

// Rule Duration
ruleDuration returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_value_0_0=RULE_INT
				{
					newLeafNode(lv_value_0_0, grammarAccess.getDurationAccess().getValueINTTerminalRuleCall_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDurationRule());
					}
					setWithLastConsumed(
						$current,
						"value",
						lv_value_0_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getDurationAccess().getUnitTimeUnitEnumRuleCall_1_0());
				}
				lv_unit_1_0=ruleTimeUnit
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDurationRule());
					}
					set(
						$current,
						"unit",
						lv_unit_1_0,
						"elixir.of.things.ElixirOfThings.TimeUnit");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Rule SensorType
ruleSensorType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='TEMP_DS18B20'
			{
				$current = grammarAccess.getSensorTypeAccess().getTEMP_DS18B20EnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getSensorTypeAccess().getTEMP_DS18B20EnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='TEMP_DHT22'
			{
				$current = grammarAccess.getSensorTypeAccess().getTEMP_DHT22EnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getSensorTypeAccess().getTEMP_DHT22EnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='HUMIDITY'
			{
				$current = grammarAccess.getSensorTypeAccess().getHUMIDITYEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getSensorTypeAccess().getHUMIDITYEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='MOTION_PIR'
			{
				$current = grammarAccess.getSensorTypeAccess().getMOTION_PIREnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getSensorTypeAccess().getMOTION_PIREnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='LIGHT'
			{
				$current = grammarAccess.getSensorTypeAccess().getLIGHTEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getSensorTypeAccess().getLIGHTEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='DISTANCE'
			{
				$current = grammarAccess.getSensorTypeAccess().getDISTANCEEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getSensorTypeAccess().getDISTANCEEnumLiteralDeclaration_5());
			}
		)
	)
;

// Rule ActuatorType
ruleActuatorType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='RELAY'
			{
				$current = grammarAccess.getActuatorTypeAccess().getRELAYEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getActuatorTypeAccess().getRELAYEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='LED'
			{
				$current = grammarAccess.getActuatorTypeAccess().getLEDEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getActuatorTypeAccess().getLEDEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='BUZZER'
			{
				$current = grammarAccess.getActuatorTypeAccess().getBUZZEREnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getActuatorTypeAccess().getBUZZEREnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='SERVO'
			{
				$current = grammarAccess.getActuatorTypeAccess().getSERVOEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getActuatorTypeAccess().getSERVOEnumLiteralDeclaration_3());
			}
		)
	)
;

// Rule QoS
ruleQoS returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='AT_MOST_ONCE'
			{
				$current = grammarAccess.getQoSAccess().getAT_MOST_ONCEEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getQoSAccess().getAT_MOST_ONCEEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='AT_LEAST_ONCE'
			{
				$current = grammarAccess.getQoSAccess().getAT_LEAST_ONCEEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getQoSAccess().getAT_LEAST_ONCEEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='EXACTLY_ONCE'
			{
				$current = grammarAccess.getQoSAccess().getEXACTLY_ONCEEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getQoSAccess().getEXACTLY_ONCEEnumLiteralDeclaration_2());
			}
		)
	)
;

// Rule Operator
ruleOperator returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='>'
			{
				$current = grammarAccess.getOperatorAccess().getGREATER_THANEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getOperatorAccess().getGREATER_THANEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='<'
			{
				$current = grammarAccess.getOperatorAccess().getLESS_THANEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getOperatorAccess().getLESS_THANEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='>='
			{
				$current = grammarAccess.getOperatorAccess().getGREATER_EQEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getOperatorAccess().getGREATER_EQEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='<='
			{
				$current = grammarAccess.getOperatorAccess().getLESS_EQEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getOperatorAccess().getLESS_EQEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='=='
			{
				$current = grammarAccess.getOperatorAccess().getEQUALSEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getOperatorAccess().getEQUALSEnumLiteralDeclaration_4());
			}
		)
	)
;

// Rule LogicalOp
ruleLogicalOp returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='and'
			{
				$current = grammarAccess.getLogicalOpAccess().getANDEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getLogicalOpAccess().getANDEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='or'
			{
				$current = grammarAccess.getLogicalOpAccess().getOREnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getLogicalOpAccess().getOREnumLiteralDeclaration_1());
			}
		)
	)
;

// Rule State
ruleState returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='ON'
			{
				$current = grammarAccess.getStateAccess().getONEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getStateAccess().getONEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='OFF'
			{
				$current = grammarAccess.getStateAccess().getOFFEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getStateAccess().getOFFEnumLiteralDeclaration_1());
			}
		)
	)
;

// Rule TimeUnit
ruleTimeUnit returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='sec'
			{
				$current = grammarAccess.getTimeUnitAccess().getSECEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getTimeUnitAccess().getSECEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='min'
			{
				$current = grammarAccess.getTimeUnitAccess().getMINEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getTimeUnitAccess().getMINEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='ms'
			{
				$current = grammarAccess.getTimeUnitAccess().getMSEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getTimeUnitAccess().getMSEnumLiteralDeclaration_2());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
