/*
 * generated by Xtext 2.41.0
 */
package elixir.of.things.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import elixir.of.things.ide.contentassist.antlr.internal.InternalElixirOfThingsParser;
import elixir.of.things.services.ElixirOfThingsGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ElixirOfThingsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ElixirOfThingsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ElixirOfThingsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSystemAccess().getAlternatives_6(), "rule__System__Alternatives_6");
			builder.put(grammarAccess.getNumExprAccess().getAlternatives_1_0(), "rule__NumExpr__Alternatives_1_0");
			builder.put(grammarAccess.getNumMulAccess().getAlternatives_1_0(), "rule__NumMul__Alternatives_1_0");
			builder.put(grammarAccess.getNumAtomAccess().getAlternatives(), "rule__NumAtom__Alternatives");
			builder.put(grammarAccess.getPublishFieldAccess().getAlternatives(), "rule__PublishField__Alternatives");
			builder.put(grammarAccess.getBoolNotAccess().getAlternatives(), "rule__BoolNot__Alternatives");
			builder.put(grammarAccess.getBoolAtomAccess().getAlternatives(), "rule__BoolAtom__Alternatives");
			builder.put(grammarAccess.getSensorTypeAccess().getAlternatives(), "rule__SensorType__Alternatives");
			builder.put(grammarAccess.getActuatorTypeAccess().getAlternatives(), "rule__ActuatorType__Alternatives");
			builder.put(grammarAccess.getQoSAccess().getAlternatives(), "rule__QoS__Alternatives");
			builder.put(grammarAccess.getOperatorAccess().getAlternatives(), "rule__Operator__Alternatives");
			builder.put(grammarAccess.getStateAccess().getAlternatives(), "rule__State__Alternatives");
			builder.put(grammarAccess.getTimeUnitAccess().getAlternatives(), "rule__TimeUnit__Alternatives");
			builder.put(grammarAccess.getSystemAccess().getGroup(), "rule__System__Group__0");
			builder.put(grammarAccess.getBrokerAccess().getGroup(), "rule__Broker__Group__0");
			builder.put(grammarAccess.getNodeAccess().getGroup(), "rule__Node__Group__0");
			builder.put(grammarAccess.getTopicAccess().getGroup(), "rule__Topic__Group__0");
			builder.put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
			builder.put(grammarAccess.getSampleRateAccess().getGroup(), "rule__SampleRate__Group__0");
			builder.put(grammarAccess.getNumExprAccess().getGroup(), "rule__NumExpr__Group__0");
			builder.put(grammarAccess.getNumExprAccess().getGroup_1(), "rule__NumExpr__Group_1__0");
			builder.put(grammarAccess.getNumExprAccess().getGroup_1_0_0(), "rule__NumExpr__Group_1_0_0__0");
			builder.put(grammarAccess.getNumExprAccess().getGroup_1_0_1(), "rule__NumExpr__Group_1_0_1__0");
			builder.put(grammarAccess.getNumMulAccess().getGroup(), "rule__NumMul__Group__0");
			builder.put(grammarAccess.getNumMulAccess().getGroup_1(), "rule__NumMul__Group_1__0");
			builder.put(grammarAccess.getNumMulAccess().getGroup_1_0_0(), "rule__NumMul__Group_1_0_0__0");
			builder.put(grammarAccess.getNumMulAccess().getGroup_1_0_1(), "rule__NumMul__Group_1_0_1__0");
			builder.put(grammarAccess.getNumAtomAccess().getGroup_0(), "rule__NumAtom__Group_0__0");
			builder.put(grammarAccess.getNumAtomAccess().getGroup_1(), "rule__NumAtom__Group_1__0");
			builder.put(grammarAccess.getTriggerAccess().getGroup(), "rule__Trigger__Group__0");
			builder.put(grammarAccess.getTriggerConditionAccess().getGroup(), "rule__TriggerCondition__Group__0");
			builder.put(grammarAccess.getTriggerActionAccess().getGroup(), "rule__TriggerAction__Group__0");
			builder.put(grammarAccess.getTriggerActionAccess().getGroup_5(), "rule__TriggerAction__Group_5__0");
			builder.put(grammarAccess.getPublishFieldAccess().getGroup_0(), "rule__PublishField__Group_0__0");
			builder.put(grammarAccess.getPublishFieldAccess().getGroup_1(), "rule__PublishField__Group_1__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup(), "rule__Actuator__Group__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup_11(), "rule__Actuator__Group_11__0");
			builder.put(grammarAccess.getOnMessageAccess().getGroup(), "rule__OnMessage__Group__0");
			builder.put(grammarAccess.getOnMessageAccess().getGroup_7(), "rule__OnMessage__Group_7__0");
			builder.put(grammarAccess.getCoordinatorAccess().getGroup(), "rule__Coordinator__Group__0");
			builder.put(grammarAccess.getCoordinatorAccess().getGroup_7(), "rule__Coordinator__Group_7__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getRuleConditionAccess().getGroup(), "rule__RuleCondition__Group__0");
			builder.put(grammarAccess.getBoolOrAccess().getGroup(), "rule__BoolOr__Group__0");
			builder.put(grammarAccess.getBoolOrAccess().getGroup_1(), "rule__BoolOr__Group_1__0");
			builder.put(grammarAccess.getBoolAndAccess().getGroup(), "rule__BoolAnd__Group__0");
			builder.put(grammarAccess.getBoolAndAccess().getGroup_1(), "rule__BoolAnd__Group_1__0");
			builder.put(grammarAccess.getBoolNotAccess().getGroup_0(), "rule__BoolNot__Group_0__0");
			builder.put(grammarAccess.getBoolAtomAccess().getGroup_0(), "rule__BoolAtom__Group_0__0");
			builder.put(grammarAccess.getBoolAtomAccess().getGroup_1(), "rule__BoolAtom__Group_1__0");
			builder.put(grammarAccess.getRuleActionAccess().getGroup(), "rule__RuleAction__Group__0");
			builder.put(grammarAccess.getRuleActionAccess().getGroup_4(), "rule__RuleAction__Group_4__0");
			builder.put(grammarAccess.getSystemAccess().getNameAssignment_1(), "rule__System__NameAssignment_1");
			builder.put(grammarAccess.getSystemAccess().getBrokerAssignment_3(), "rule__System__BrokerAssignment_3");
			builder.put(grammarAccess.getSystemAccess().getNodesAssignment_4(), "rule__System__NodesAssignment_4");
			builder.put(grammarAccess.getSystemAccess().getTopicsAssignment_5(), "rule__System__TopicsAssignment_5");
			builder.put(grammarAccess.getSystemAccess().getSensorsAssignment_6_0(), "rule__System__SensorsAssignment_6_0");
			builder.put(grammarAccess.getSystemAccess().getActuatorsAssignment_6_1(), "rule__System__ActuatorsAssignment_6_1");
			builder.put(grammarAccess.getSystemAccess().getCoordinatorsAssignment_6_2(), "rule__System__CoordinatorsAssignment_6_2");
			builder.put(grammarAccess.getBrokerAccess().getHostAssignment_1(), "rule__Broker__HostAssignment_1");
			builder.put(grammarAccess.getBrokerAccess().getPortAssignment_3(), "rule__Broker__PortAssignment_3");
			builder.put(grammarAccess.getNodeAccess().getNameAssignment_1(), "rule__Node__NameAssignment_1");
			builder.put(grammarAccess.getTopicAccess().getNameAssignment_1(), "rule__Topic__NameAssignment_1");
			builder.put(grammarAccess.getTopicAccess().getTopicStringAssignment_4(), "rule__Topic__TopicStringAssignment_4");
			builder.put(grammarAccess.getTopicAccess().getQosAssignment_6(), "rule__Topic__QosAssignment_6");
			builder.put(grammarAccess.getSensorAccess().getNameAssignment_1(), "rule__Sensor__NameAssignment_1");
			builder.put(grammarAccess.getSensorAccess().getTypeAssignment_4(), "rule__Sensor__TypeAssignment_4");
			builder.put(grammarAccess.getSensorAccess().getGpioPinAssignment_6(), "rule__Sensor__GpioPinAssignment_6");
			builder.put(grammarAccess.getSensorAccess().getSampleRateAssignment_8(), "rule__Sensor__SampleRateAssignment_8");
			builder.put(grammarAccess.getSensorAccess().getDeployedOnAssignment_10(), "rule__Sensor__DeployedOnAssignment_10");
			builder.put(grammarAccess.getSensorAccess().getTriggersAssignment_11(), "rule__Sensor__TriggersAssignment_11");
			builder.put(grammarAccess.getSampleRateAccess().getValueAssignment_0(), "rule__SampleRate__ValueAssignment_0");
			builder.put(grammarAccess.getSampleRateAccess().getUnitAssignment_1(), "rule__SampleRate__UnitAssignment_1");
			builder.put(grammarAccess.getNumExprAccess().getRightAssignment_1_1(), "rule__NumExpr__RightAssignment_1_1");
			builder.put(grammarAccess.getNumMulAccess().getRightAssignment_1_1(), "rule__NumMul__RightAssignment_1_1");
			builder.put(grammarAccess.getNumAtomAccess().getValueAssignment_0_1(), "rule__NumAtom__ValueAssignment_0_1");
			builder.put(grammarAccess.getTriggerAccess().getNameAssignment_1(), "rule__Trigger__NameAssignment_1");
			builder.put(grammarAccess.getTriggerAccess().getConditionAssignment_3(), "rule__Trigger__ConditionAssignment_3");
			builder.put(grammarAccess.getTriggerAccess().getActionsAssignment_4(), "rule__Trigger__ActionsAssignment_4");
			builder.put(grammarAccess.getTriggerConditionAccess().getOperatorAssignment_2(), "rule__TriggerCondition__OperatorAssignment_2");
			builder.put(grammarAccess.getTriggerConditionAccess().getRightAssignment_3(), "rule__TriggerCondition__RightAssignment_3");
			builder.put(grammarAccess.getTriggerActionAccess().getTopicAssignment_1(), "rule__TriggerAction__TopicAssignment_1");
			builder.put(grammarAccess.getTriggerActionAccess().getFieldsAssignment_4(), "rule__TriggerAction__FieldsAssignment_4");
			builder.put(grammarAccess.getTriggerActionAccess().getFieldsAssignment_5_1(), "rule__TriggerAction__FieldsAssignment_5_1");
			builder.put(grammarAccess.getActuatorAccess().getNameAssignment_1(), "rule__Actuator__NameAssignment_1");
			builder.put(grammarAccess.getActuatorAccess().getTypeAssignment_4(), "rule__Actuator__TypeAssignment_4");
			builder.put(grammarAccess.getActuatorAccess().getGpioPinAssignment_6(), "rule__Actuator__GpioPinAssignment_6");
			builder.put(grammarAccess.getActuatorAccess().getDeployedOnAssignment_8(), "rule__Actuator__DeployedOnAssignment_8");
			builder.put(grammarAccess.getActuatorAccess().getSubscribeToAssignment_10(), "rule__Actuator__SubscribeToAssignment_10");
			builder.put(grammarAccess.getActuatorAccess().getSubscribeToAssignment_11_1(), "rule__Actuator__SubscribeToAssignment_11_1");
			builder.put(grammarAccess.getActuatorAccess().getMessagesAssignment_12(), "rule__Actuator__MessagesAssignment_12");
			builder.put(grammarAccess.getOnMessageAccess().getTopicAssignment_3(), "rule__OnMessage__TopicAssignment_3");
			builder.put(grammarAccess.getOnMessageAccess().getStateAssignment_6(), "rule__OnMessage__StateAssignment_6");
			builder.put(grammarAccess.getOnMessageAccess().getDurationAssignment_7_1(), "rule__OnMessage__DurationAssignment_7_1");
			builder.put(grammarAccess.getCoordinatorAccess().getNameAssignment_1(), "rule__Coordinator__NameAssignment_1");
			builder.put(grammarAccess.getCoordinatorAccess().getDeployedOnAssignment_4(), "rule__Coordinator__DeployedOnAssignment_4");
			builder.put(grammarAccess.getCoordinatorAccess().getSubscribeToAssignment_6(), "rule__Coordinator__SubscribeToAssignment_6");
			builder.put(grammarAccess.getCoordinatorAccess().getSubscribeToAssignment_7_1(), "rule__Coordinator__SubscribeToAssignment_7_1");
			builder.put(grammarAccess.getCoordinatorAccess().getRulesAssignment_8(), "rule__Coordinator__RulesAssignment_8");
			builder.put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
			builder.put(grammarAccess.getRuleAccess().getConditionAssignment_3(), "rule__Rule__ConditionAssignment_3");
			builder.put(grammarAccess.getRuleAccess().getActionsAssignment_4(), "rule__Rule__ActionsAssignment_4");
			builder.put(grammarAccess.getRuleConditionAccess().getExpressionAssignment_1(), "rule__RuleCondition__ExpressionAssignment_1");
			builder.put(grammarAccess.getBoolOrAccess().getRightAssignment_1_2(), "rule__BoolOr__RightAssignment_1_2");
			builder.put(grammarAccess.getBoolAndAccess().getRightAssignment_1_2(), "rule__BoolAnd__RightAssignment_1_2");
			builder.put(grammarAccess.getBoolNotAccess().getOperandAssignment_0_2(), "rule__BoolNot__OperandAssignment_0_2");
			builder.put(grammarAccess.getBoolAtomAccess().getTopicAssignment_0_1(), "rule__BoolAtom__TopicAssignment_0_1");
			builder.put(grammarAccess.getRuleActionAccess().getTopicAssignment_1(), "rule__RuleAction__TopicAssignment_1");
			builder.put(grammarAccess.getRuleActionAccess().getMessageAssignment_4_1(), "rule__RuleAction__MessageAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ElixirOfThingsGrammarAccess grammarAccess;

	@Override
	protected InternalElixirOfThingsParser createParser() {
		InternalElixirOfThingsParser result = new InternalElixirOfThingsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ElixirOfThingsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ElixirOfThingsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
