---
config:
  theme: redux
  layout: elk
  look: neo
---
classDiagram
direction TB
    class System {
	    name: String
    }

    class Broker {
	    host: String
	    port: Integer
    }

    class Node {
	    name: String
    }

    class Topic {
	    name: String
	    topicString: String
	    external: Boolean
    }

    class Sensor {
	    name: String
	    type: SensorType
	    gpioPin: Integer
    }

    class SampleRate {
	    unit: TimeUnit
    }

    class Actuator {
	    name: String
	    type: ActuatorType
	    gpioPin: Integer
    }

    class OnMessage {
	    state: State
    }

    class Coordinator {
	    name: String
    }

    class Trigger {
	    name: String
    }

    class TriggerCondition {
	    operator: Operator
    }

    class TriggerAction {
    }

    class PublishField {
    }

    class ValueField {
    }

    class TimestampField {
    }

    class Rule {
	    name: String
    }

    class RuleCondition {
    }

    class RuleAction {
	    message: String
    }

    class Expression {
    }

    class NumericLiteral {
	    value: Integer
    }

    class BinaryExpression {
	    operator: String
    }

    class BooleanExpression {
    }

    class BooleanBinary {
	    operator: LogicalOperator
    }

    class BooleanNot {
    }

    class TopicReference {
    }

    class SensorType {
	    TEMP_DS18B20
	    TEMP_DHT22
	    HUMIDITY
	    MOTION_PIR
	    LIGHT
	    DISTANCE
    }

    class ActuatorType {
	    RELAY
	    LED
	    BUZZER
	    SERVO
    }

    class QoS {
	    AT_MOST_ONCE
	    AT_LEAST_ONCE
	    EXACTLY_ONCE
    }

    class Operator {
	    GREATER_THAN
	    LESS_THAN
	    GREATER_EQ
	    LESS_EQ
	    EQUALS
    }

    class LogicalOperator {
	    AND
	    OR
    }

    class State {
	    ON
	    OFF
    }

    class TimeUnit {
	    SEC
	    MIN
	    MS
    }


	<<abstract>> PublishField
	<<abstract>> Expression
	<<abstract>> BooleanExpression
	<<enumeration>> SensorType
	<<enumeration>> ActuatorType
	<<enumeration>> QoS
	<<enumeration>> Operator
	<<enumeration>> LogicalOperator
	<<enumeration>> State
	<<enumeration>> TimeUnit

    System "1" *-- "1" Broker
    System "1" *-- "1..*" Node
    System "1" *-- "0..*" Topic
    System "1" *-- "0..*" Sensor
    System "1" *-- "0..*" Actuator
    System "1" *-- "0..*" Coordinator
    Sensor --> Node : deployedOn
    Sensor *-- "1" SampleRate : sampleRate
    Sensor *-- "0..*" Trigger : triggers
    Sensor ..> SensorType : type
    SampleRate --> Expression : value
    SampleRate ..> TimeUnit : unit
    Expression <|-- NumericLiteral
    Expression <|-- BinaryExpression
    BinaryExpression --> Expression : left
    BinaryExpression --> Expression : right
    Trigger *-- "1" TriggerCondition : condition
    Trigger *-- "1..*" TriggerAction : actions
    TriggerCondition ..> Operator : operator
    TriggerCondition --> Expression : right
    TriggerAction --> Topic : topic
    TriggerAction *-- "1..*" PublishField : fields
    PublishField <|-- ValueField
    PublishField <|-- TimestampField
    Actuator --> Node : deployedOn
    Actuator --> "1..*" Topic : subscribeTo
    Actuator *-- "0..*" OnMessage : messages
    Actuator ..> ActuatorType : type
    OnMessage --> Topic : from
    OnMessage ..> State : state
    OnMessage *-- "0..1" SampleRate : duration
    Coordinator --> Node : deployedOn
    Coordinator --> "1..*" Topic : subscribeTo
    Coordinator *-- "0..*" Rule : rules
    Rule *-- "1" RuleCondition : condition
    Rule *-- "1..*" RuleAction : actions
    RuleCondition --> BooleanExpression : expression
    BooleanExpression <|-- BooleanBinary
    BooleanExpression <|-- BooleanNot
    BooleanExpression <|-- TopicReference
    BooleanBinary --> BooleanExpression : left
    BooleanBinary --> BooleanExpression : right
    BooleanBinary ..> LogicalOperator : operator
    BooleanNot --> BooleanExpression : operand
    TopicReference --> Topic : topic
    RuleAction --> Topic : topic
    Topic ..> QoS : qos