/*
 * generated by Xtext 2.41.0
 */
package elixir.of.things.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractElixirOfThingsScopeProvider extends DelegatingScopeProvider {
}
