grammar elixir.of.things.ElixirOfThings with org.eclipse.xtext.common.Terminals

generate elixirOfThings "http://www.of.elixir/things/ElixirOfThings"

// ─── Root ──────────────────────────────────────────────────────────────────
System:
    'system' name=ID '{'
        broker=Broker
        nodes+=Node+
        topics+=Topic*
        (sensors+=Sensor | actuators+=Actuator | coordinators+=Coordinator)*
    '}';

Broker:
    'broker:' host=STRING 'port:' port=INT;


Node:
    'node' name=ID;

Topic:
    'topic' name=ID '=' '(' topicString=STRING ',' qos=QoS ')';

Sensor:
    'sensor' name=ID '{'
        'type:' type=SensorType
        'gpioPin:' gpioPin=INT
        'sampleRate:' sampleRate=Duration
        'deployedOn:' deployedOn=[Node]
        triggers+=Trigger*
    '}';

Trigger:
    'trigger' name=ID '{'
        condition=TriggerCondition
        actions+=TriggerAction+
    '}';

TriggerCondition:
    'when' 'value' operator=Operator right=INT ':';

TriggerAction:
    'publish' topic=[Topic] ':' '{' fields+=PublishField (',' fields+=PublishField)* '}';

PublishField:
    {ValueField}     'value'     |
    {TimestampField} 'timestamp';

Actuator:
    'actuator' name=ID '{'
        'type:' type=ActuatorType
        'gpioPin:' gpioPin=INT
        'deployedOn:' deployedOn=[Node]
        'subscribeTo:' subscribeTo+=[Topic] (',' subscribeTo+=[Topic])*
        messages+=OnMessage*
    '}';

OnMessage:
    'on' 'message' 'from' topic=[Topic] ':'
        'turn' state=State ('for' duration=Duration)?;

Coordinator:
    'coordinator' name=ID '{'
        'deployedOn:' deployedOn=[Node]
        'subscribeTo:' subscribeTo+=[Topic] (',' subscribeTo+=[Topic])*
        rules+=Rule*
    '}';

Rule:
    'rule' name=ID '{'
        condition=RuleCondition
        actions+=RuleAction+
    '}';

RuleCondition:
    'when' topics+=[Topic] (operators+=LogicalOp topics+=[Topic])* ':';

RuleAction:
    'publish' topic=[Topic] ':' '{' ('message:' message=STRING)? '}';

Duration:
    value=INT unit=TimeUnit;

enum SensorType:
    TEMP_DS18B20 | TEMP_DHT22 | HUMIDITY | MOTION_PIR | LIGHT | DISTANCE;

enum ActuatorType:
    RELAY | LED | BUZZER | SERVO;

enum QoS:
    AT_MOST_ONCE | AT_LEAST_ONCE | EXACTLY_ONCE;

enum Operator:
    GREATER_THAN='>' | LESS_THAN='<' | GREATER_EQ='>=' | LESS_EQ='<=' | EQUALS='==';

enum LogicalOp:
    AND='and' | OR='or';

enum State:
    ON | OFF;

enum TimeUnit:
    SEC='sec' | MIN='min' | MS='ms';
